### ISSUE TITLE
Exception occurs in ProtocolProcessor during publishing, after unexpected termination.

### ISSUE THREAD

**Issue by runafter** [moquette-io/moquette#104]
If moquette server is terminated unexpectly during some clinets is connected with subscribing, subscription.active value remain to 'true' in MapDB file.
This makes a Exception during next publishing process.

```
18:02:19,778 [main] INFO  Server startServer 95  - Persistent store file: C:\Users\runafter\git\runafter\moquette\broker\moquette_store.mapdb
18:02:20,110 [main] DEBUG SubscriptionsStore init 102  - init invoked
18:02:20,113 [main] DEBUG SubscriptionsStore init 107  - Reloading all stored subscriptions...subscription tree before 

18:02:20,113 [main] DEBUG SubscriptionsStore init 115  - Finished loading. Subscription tree after 

18:02:20,114 [main] DEBUG ProtocolProcessor init 137  - subscription tree on init 

18:02:20,363 [main] INFO  NettyAcceptor initFactory 145  - Server binded host: 0.0.0.0, port: 1883
18:02:20,366 [main] INFO  NettyAcceptor initFactory 145  - Server binded host: 0.0.0.0, port: 8080
18:02:20,538 [pool-1-thread-1] DEBUG ProtocolProcessor processConnect 160  - CONNECT for client <clientForSubscribe1>
18:02:20,538 [pool-1-thread-1] DEBUG ProtocolProcessor processConnect 216  - Connect with keepAlive 60 s
18:02:20,539 [pool-1-thread-1] DEBUG ProtocolProcessor processConnect 221  - Connect create session <session [clientID: clientForSubscribe1]org.eclipse.moquette.server.netty.NettyChannel@1ba0f6dd>
18:02:20,540 [pool-1-thread-1] DEBUG SubscriptionsStore activate 209  - Activating subscriptions for clientID <clientForSubscribe1>
18:02:20,543 [pool-1-thread-1] INFO  ProtocolProcessor processConnect 257  - Connected client ID <clientForSubscribe1> with clean session false
18:02:20,544 [pool-1-thread-1] INFO  ProtocolProcessor republishStoredInSession 278  - No stored messages for client <clientForSubscribe1>
18:02:20,562 [pool-1-thread-1] DEBUG ProtocolProcessor processSubscribe 633  - SUBSCRIBE client <clientForSubscribe1> packetID 1
18:02:20,563 [pool-1-thread-1] INFO  ProtocolProcessor subscribeSingleTopic 651  - <clientForSubscribe1> subscribed to topic </topic> with QoS 2 - EXACTLY_ONCE
18:02:20,572 [pool-1-thread-1] DEBUG ProtocolProcessor processSubscribe 646  - SUBACK for packetID 1
18:02:20,576 [main] INFO  Server stopServer 104  - Server stopping...
18:02:20,593 [pool-1-thread-1] INFO  ProtocolProcessor processConnectionLost 586  - Lost connection with client <clientForSubscribe1>
18:02:20,796 [main] INFO  NettyAcceptor close 291  - Msg read: 2, msg wrote: 2
18:02:20,797 [main] INFO  NettyAcceptor close 294  - Bytes read: 48, bytes wrote: 503
18:02:20,888 [main] INFO  Server stopServer 107  - Server stopped
18:02:20,952 [main] INFO  Server startServer 95  - Persistent store file: C:\Users\runafter\git\runafter\moquette\broker\moquette_store.mapdb
18:02:20,991 [main] DEBUG SubscriptionsStore init 102  - init invoked
18:02:20,991 [main] DEBUG SubscriptionsStore init 107  - Reloading all stored subscriptions...subscription tree before 

18:02:20,991 [main] DEBUG SubscriptionsStore init 111  - Re-subscribing clientForSubscribe1 to topic /topic
18:02:20,992 [main] DEBUG SubscriptionsStore init 115  - Finished loading. Subscription tree after 

    topic
        [filter:/topic, cliID: clientForSubscribe1, qos: EXACTLY_ONCE, active: true]

18:02:20,992 [main] DEBUG ProtocolProcessor init 137  - subscription tree on init 

    topic
        [filter:/topic, cliID: clientForSubscribe1, qos: EXACTLY_ONCE, active: true]

18:02:21,021 [main] INFO  NettyAcceptor initFactory 145  - Server binded host: 0.0.0.0, port: 1883
18:02:21,022 [main] INFO  NettyAcceptor initFactory 145  - Server binded host: 0.0.0.0, port: 8080
18:02:21,026 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 160  - CONNECT for client <clientForSubscribe2>
18:02:21,026 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 216  - Connect with keepAlive 60 s
18:02:21,026 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 221  - Connect create session <session [clientID: clientForSubscribe2]org.eclipse.moquette.server.netty.NettyChannel@3e78c47c>
18:02:21,027 [pool-6-thread-1] DEBUG SubscriptionsStore activate 209  - Activating subscriptions for clientID <clientForSubscribe2>
18:02:21,027 [pool-6-thread-1] INFO  ProtocolProcessor processConnect 257  - Connected client ID <clientForSubscribe2> with clean session false
18:02:21,027 [pool-6-thread-1] INFO  ProtocolProcessor republishStoredInSession 278  - No stored messages for client <clientForSubscribe2>
18:02:21,028 [pool-6-thread-1] DEBUG ProtocolProcessor processSubscribe 633  - SUBSCRIBE client <clientForSubscribe2> packetID 1
18:02:21,028 [pool-6-thread-1] INFO  ProtocolProcessor subscribeSingleTopic 651  - <clientForSubscribe2> subscribed to topic </topic> with QoS 2 - EXACTLY_ONCE
18:02:21,029 [pool-6-thread-1] DEBUG ProtocolProcessor processSubscribe 646  - SUBACK for packetID 1
18:02:21,030 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 160  - CONNECT for client <clientForPublish>
18:02:21,031 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 216  - Connect with keepAlive 60 s
18:02:21,031 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 221  - Connect create session <session [clientID: clientForPublish]org.eclipse.moquette.server.netty.NettyChannel@50103bfb>
18:02:21,031 [pool-6-thread-1] DEBUG SubscriptionsStore activate 209  - Activating subscriptions for clientID <clientForPublish>
18:02:21,031 [pool-6-thread-1] INFO  ProtocolProcessor processConnect 257  - Connected client ID <clientForPublish> with clean session false
18:02:21,032 [pool-6-thread-1] INFO  ProtocolProcessor republishStoredInSession 278  - No stored messages for client <clientForPublish>
18:02:21,032 [nioEventLoopGroup-5-2] INFO  PublishDecoder decode 38  - decode invoked with buffer UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 19, cap: 1024)
18:02:21,033 [pool-6-thread-1] INFO  ProtocolProcessor executePublish 329  - PUBLISH from clientID <clientForPublish> on topic </topic> with QoS EXACTLY_ONCE
18:02:21,035 [pool-6-thread-1] DEBUG ProtocolProcessor disruptorPublish 684  - disruptorPublish publishing event on output org.eclipse.moquette.spi.impl.events.OutputMessagingEvent@321881a2
18:02:21,035 [pool-9-thread-1] DEBUG ProtocolProcessor onEvent 698  - Output event, sending org.eclipse.moquette.proto.messages.PubRecMessage@66e6cc5f
18:02:21,037 [pool-6-thread-1] DEBUG ProtocolProcessor processPubRel 510  - PUB --PUBREL--> SRV processPubRel invoked for clientID clientForPublish ad messageID 1
18:02:21,037 [pool-6-thread-1] DEBUG ProtocolProcessor forward2Subscribers 387  - forward2Subscribers republishing to existing subscribers that matches the topic /topic
18:02:21,037 [pool-6-thread-1] DEBUG ProtocolProcessor forward2Subscribers 389  - content <message>
18:02:21,038 [pool-6-thread-1] DEBUG ProtocolProcessor forward2Subscribers 390  - subscription tree 

    topic
        [filter:/topic, cliID: clientForSubscribe1, qos: EXACTLY_ONCE, active: true]
        [filter:/topic, cliID: clientForSubscribe2, qos: EXACTLY_ONCE, active: true]

18:02:21,038 [pool-6-thread-1] DEBUG ProtocolProcessor forward2Subscribers 398  - Broker republishing to client <clientForSubscribe1> topic </topic> qos <EXACTLY_ONCE>, active true
18:02:21,039 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 430  - sendPublish invoked clientId <clientForSubscribe1> on topic </topic> QoS EXACTLY_ONCE retained false messageID 1
18:02:21,039 [pool-6-thread-1] INFO  ProtocolProcessor sendPublish 437  - send publish message to <clientForSubscribe1> on topic </topic>
18:02:21,039 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 439  - content <message>
18:02:21,039 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 453  - clientIDs are {clientForSubscribe2=ConnectionDescriptor{m_clientID=clientForSubscribe2, m_cleanSession=false}, clientForPublish=ConnectionDescriptor{m_clientID=clientForPublish, m_cleanSession=false}}
18:02:21,040 [pool-6-thread-1] ERROR SimpleMessaging onEvent 182  - Serious error processing the message org.eclipse.moquette.proto.messages.PubRelMessage@44c7c82a for session [clientID: clientForPublish]org.eclipse.moquette.server.netty.NettyChannel@182660ad
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:176)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <clientForSubscribe1> in cache <{clientForSubscribe2=ConnectionDescriptor{m_clientID=clientForSubscribe2, m_cleanSession=false}, clientForPublish=ConnectionDescriptor{m_clientID=clientForPublish, m_cleanSession=false}}>
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:455)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.forward2Subscribers(ProtocolProcessor.java:422)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPubRel(ProtocolProcessor.java:513)
    ... 11 more
18:02:21,099 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 160  - CONNECT for client <clientForSubscribe1>
18:02:21,099 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 216  - Connect with keepAlive 60 s
18:02:21,099 [pool-6-thread-1] DEBUG ProtocolProcessor processConnect 221  - Connect create session <session [clientID: clientForSubscribe1]org.eclipse.moquette.server.netty.NettyChannel@498394b0>
18:02:21,100 [pool-6-thread-1] DEBUG SubscriptionsStore activate 209  - Activating subscriptions for clientID <clientForSubscribe1>
18:02:21,101 [pool-6-thread-1] INFO  ProtocolProcessor processConnect 257  - Connected client ID <clientForSubscribe1> with clean session false
18:02:21,101 [pool-6-thread-1] INFO  ProtocolProcessor republishStoredInSession 278  - No stored messages for client <clientForSubscribe1>
18:02:21,102 [pool-6-thread-1] DEBUG ProtocolProcessor processSubscribe 633  - SUBSCRIBE client <clientForSubscribe1> packetID 2
18:02:21,102 [pool-6-thread-1] INFO  ProtocolProcessor subscribeSingleTopic 651  - <clientForSubscribe1> subscribed to topic </topic> with QoS 2 - EXACTLY_ONCE
18:02:21,103 [pool-6-thread-1] DEBUG ProtocolProcessor subscribeSingleTopic 674  - send publish message for topic /topic
18:02:21,103 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 430  - sendPublish invoked clientId <clientForSubscribe1> on topic </topic> QoS EXACTLY_ONCE retained true messageID 2
18:02:21,104 [pool-6-thread-1] INFO  ProtocolProcessor sendPublish 437  - send publish message to <clientForSubscribe1> on topic </topic>
18:02:21,104 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 439  - content <message>
18:02:21,104 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 453  - clientIDs are {clientForSubscribe1=ConnectionDescriptor{m_clientID=clientForSubscribe1, m_cleanSession=false}, clientForSubscribe2=ConnectionDescriptor{m_clientID=clientForSubscribe2, m_cleanSession=false}, clientForPublish=ConnectionDescriptor{m_clientID=clientForPublish, m_cleanSession=false}}
18:02:21,104 [pool-6-thread-1] DEBUG ProtocolProcessor sendPublish 458  - Session for clientId clientForSubscribe1 is session [clientID: clientForSubscribe1]org.eclipse.moquette.server.netty.NettyChannel@498394b0
18:02:21,104 [pool-6-thread-1] DEBUG ProtocolProcessor disruptorPublish 684  - disruptorPublish publishing event on output org.eclipse.moquette.spi.impl.events.OutputMessagingEvent@39cb7618
18:02:21,105 [pool-6-thread-1] DEBUG ProtocolProcessor processSubscribe 646  - SUBACK for packetID 2
18:02:21,105 [pool-9-thread-1] DEBUG ProtocolProcessor onEvent 698  - Output event, sending org.eclipse.moquette.proto.messages.PublishMessage@5cb63f4c

```

When a client publish, ProtocolProcessor.forward2Subscribers() select active clients in subscrptions to publishing.
But some client subscription has wrong value 'active', it makes become target to send message.
And then ProtocolProcessor.sendPublish() try to use ServerChannel in ProtocolProcessor.m_clientIDs, but it is not existed.

So, how about set Subscription.active to 'false' when server startup?

Here is test code for this case.
https://github.com/runafter/moquette/commit/018707dd7ab2d8430e53f1c407a337dbabe72a8c

**Comment by andsel** [comment]
I think that the problem here is a bad management of the isActive flag. I'm going to refactory the storage part, but essentially it shouldn't be stored persistently, if a broker terminates or is shutdown, then the clients has to reconnect by themselves. The server should never persist the fact that a subscription is active or not, it has to store the messages for clients not connected and with clean session flag to false.

**Comment by andsel** [comment]
This is the same bug condition explained in issue #118
