### ISSUE TITLE
ProtocolProcessor NPE

### ISSUE THREAD

**Issue by leotu** [moquette-io/moquette#116]
Error message below:

``` java
java.lang.NullPointerException: null
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPubRec(ProtocolProcessor.java:448) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:320) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:290) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
    at org.eclipse.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:70) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
```

I use "org.eclipse.paho.client.mqttv3.MqttAsyncClient"  run client (client-X app),
that one connection is to be Subscriber (clientId-A) , and another one is to be Publisher  (clientId-B) .
There are keep connection alive.

Then, I run the same client code (client-Y app) again with the same client ids (clientId-A & clientId-B).
Previous client (client-X app) will fire "connectionLost", and "client-Y app" still to  publish topic message. The server will cause NPE at "m_clientIDs.get(clientID)" is null value.

``` java
private void sendPubRec(String clientID, int messageID) {
        LOG.trace("PUB <--PUBREC-- SRV sendPubRec invoked for clientID {} with messageID {}", clientID, messageID);
        PubRecMessage pubRecMessage = new PubRecMessage();
        pubRecMessage.setMessageID(messageID);
        m_clientIDs.get(clientID).getSession().write(pubRecMessage);
    }
```

**Comment by andsel** [comment]
Was due to bad remotion of the newly connected client descriptor
