### ISSUE TITLE
Broker restart hangs publishers

### ISSUE THREAD

**Issue by yankyo** [moquette-io/moquette#132]
Restarting the moquette broker will cause all publishers (in the new broker session) to hang forever waiting for ACKs. Reproducible always with the most recent code as of the time of writing.

Steps to reproduce:
1. Start broker
2. Start a subscriber
3. While the client is still running, stop the broker
4. Kill subscriber
5. Start a new publisher and make it publish a message -- broker will fail with the message below and the publisher will never get the message acknowledged, no matter whether the original subscriber re-connects or not.

Broker stack trace (OLD_SUB is the client from step 2, NEW_PUB from step 5):

```
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <OLD_SUB> in cache <{NEW_PUB=ConnectionDescriptor{clientID=NEW_PUB, cleanSession=true}}>
        at io.moquette.spi.impl.ProtocolProcessor.directSend(ProtocolProcessor.java:509) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:473) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.ProtocolProcessor.processPubRel(ProtocolProcessor.java:558) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:70) ~[moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46) [moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [netty-codec-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47) [moquette-broker-0.8-SNAPSHOT.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [netty-handler-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110) [netty-common-4.0.30.Final.jar:4.0.30.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.30.Final.jar:4.0.30.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

The session information seems to be persisted -- the only way to restart broker without causing this issue is to make all subscribers disconnect first.

Expected behaviour: broker, if restarted, cleans all the sessions (stopping the server will cause all clients to disconnect anyway).

**Comment by yankyo** [comment]
Changing the original exception-throwing ProtocolProcessor code from

``` java
        if (m_clientIDs.get(clientId) == null) {
            //TODO while we were publishing to the target client, that client disconnected,
            // could happen is not an error HANDLE IT
            throw new RuntimeException(String.format("Can't find a ConnectionDescriptor for client <%s> in cache <%s>", clientId, m_clientIDs));
        }
```

to

``` java
        if (m_clientIDs.get(clientId) == null) {
            LOG.error("Can't find a ConnectionDescriptor for client <" + clientId + "> in cache <" + m_clientIDs + ">, possibly dead subscriber??");
            return;
        }
```

seems to fix this particular case (and passes all the tests), but I'm not sure about the implications.

Also, it seems to be (according to the stack trace and the steps to reproduce) the same issue as https://github.com/andsel/moquette/issues/4

**Comment by andyxm** [comment]
I also encountered this problem, the solution is: change the replacement of the proxy server version 0.8 (I am using is 0.8) to solve the above

**Comment by andsel** [comment]
Hi @yankyo 
I've tried to replicate and the problem doesn't manifest (with current master 0.9-SNAPSHOT).
I've done my testing with scripts in https://github.com/andsel/moquette/tree/master/tools_scripts

For the subscription part I've used `groovy subscriber_generic.groovy localhost /test` and the publish `groovy trivialPublish.groovy  localhost /test`.

Could you test again with current master and publish somewhere the code of the clients you use

 Andrea
