### ISSUE TITLE
NullPointerException in ProtocolProcessor.republishStoredInSession(ProtocolProcessor.java:258)

### ISSUE THREAD

**Issue by andi-de** [moquette-io/moquette#151]
Version: distribution-0.8-bundle-tar.tar.gz

**Steps to reproduce**:
- Both clients are started with clean_session=False

1.) clientA: subscribe to "test/msg/#" with qos=1
2.) clientB: publish message "test" to "test/msg" with qos=1
3.) clientA receives the message as expected
3.) kill clientA
4.) clientB: publish the same message again ( "test" to "test/msg"), this time with **qos=0**
5.) start clientA
6.) The following NPE appears everytime clientA is started:

```
178607 [nioEventLoopGroup-3-2] INFO  ProtocolProcessor  - republishing stored messages to client <myClient>
178607 [nioEventLoopGroup-3-2] ERROR NettyMQTTHandler  - Bad error in processing the message
java.lang.NullPointerException
    at io.moquette.spi.impl.ProtocolProcessor.republishStoredInSession(ProtocolProcessor.java:258)
    at io.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:231)
    at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:52)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by LiangCan** [comment]
What the client you are using? You can try to replace the client .

**Comment by andsel** [comment]
The user didn't provided the required info, and the bug is not reproducible. Close it
