### ISSUE TITLE
Intermittent concurrentModificationExceptions 

### ISSUE THREAD

**Issue by kjayashankar** [moquette-io/moquette#208]
Hi, 
I'm stress testing moquette and I see lot of concurrentmodification exceptions, 
first it was in Collections.sort of MapDBSessionStore class, nextPacketID( ) method. I modified code base to not use collections.sort and used a method to get the max of collection using iterator, still I'm seeing intermittent exceptions like these :

```
22:16:09,503 [nioEventLoopGroup-3-2] ERROR NettyMQTTHandler channelRead 84  - Bad error in processing the message
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at io.moquette.spi.persistence.MapDBSessionsStore.max(MapDBSessionsStore.java:179)
    at io.moquette.spi.persistence.MapDBSessionsStore.nextPacketID(MapDBSessionsStore.java:168)
    at io.moquette.spi.ClientSession.nextPacketId(ClientSession.java:170)
    at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:555)
    at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:418)
    at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:61)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
22:16:09,505 [nioEventLoopGroup-3-2] WARN  DefaultChannelPipeline warn 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at io.moquette.spi.persistence.MapDBSessionsStore.max(MapDBSessionsStore.java:179)
    at io.moquette.spi.persistence.MapDBSessionsStore.nextPacketID(MapDBSessionsStore.java:168)
    at io.moquette.spi.ClientSession.nextPacketId(ClientSession.java:170)
    at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:555)
    at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:418)
```

**Comment by kjayashankar** [comment]
Another instance :

```
23:39:27,389 [nioEventLoopGroup-3-2] ERROR NettyMQTTHandler channelRead 84  - Bad error in processing the message
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at org.mapdb.SerializerBase.serializeMap(SerializerBase.java:818)
    at org.mapdb.SerializerBase.serialize2(SerializerBase.java:377)
    at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
    at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
    at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
    at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:129)
    at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:121)
    at org.mapdb.Store.serialize(Store.java:154)
    at org.mapdb.StoreWAL.update(StoreWAL.java:371)
    at org.mapdb.Caches$HashTable.update(Caches.java:270)
    at org.mapdb.HTreeMap.putInner(HTreeMap.java:533)
    at org.mapdb.HTreeMap.put(HTreeMap.java:488)
    at io.moquette.spi.persistence.MapDBSessionsStore.inFlight(MapDBSessionsStore.java:210)
    at io.moquette.spi.ClientSession.inFlightAckWaiting(ClientSession.java:180)
    at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:554)
    at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:416)
    at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:61)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
23:39:27,392 [nioEventLoopGroup-3-2] WARN  DefaultChannelPipeline warn 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
    at org.mapdb.SerializerBase.serializeMap(SerializerBase.java:818)
    at org.mapdb.SerializerBase.serialize2(SerializerBase.java:377)
    at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
    at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
    at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
    at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:129)
    at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:121)
    at org.mapdb.Store.serialize(Store.java:154)
    at org.mapdb.StoreWAL.update(StoreWAL.java:371)
    at org.mapdb.Caches$HashTable.update(Caches.java:270)
    at org.mapdb.HTreeMap.putInner(HTreeMap.java:533)
    at org.mapdb.HTreeMap.put(HTreeMap.java:488)
    at io.moquette.spi.persistence.MapDBSessionsStore.inFlight(MapDBSessionsStore.java:210)
    at io.moquette.spi.ClientSession.inFlightAckWaiting(ClientSession.java:180)
    at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:554)
    at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:416)
    at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:61)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by andsel** [comment]
A lot has changed, please could you test with one of the latest versions of Moquette?
