### ISSUE TITLE
server.start(config) crash

### ISSUE THREAD

**Issue by GeorgeMatveev** [moquette-io/moquette#222]
Hi, I am trying to use moquette code for custom MQTT based system.
When I run it, server.start(config) crashes with both 
default 
    IConfig config = new FilesystemConfig();

and my custom
   File configFile = new File("broker/config/moquette.conf");
which is config file from project source code and is read ok.

Here's the stack trace:

Exception in thread "main" java.io.IOError: java.io.IOException: storage has invalid header
    at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:254)
    at org.mapdb.StoreWAL.checkHeaders(StoreWAL.java:115)
    at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
    at org.mapdb.StoreWAL.<init>(StoreWAL.java:74)
    at org.mapdb.DBMaker.extendStoreWAL(DBMaker.java:981)
    at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
    at org.mapdb.DBMaker.make(DBMaker.java:701)
    at io.moquette.spi.persistence.MapDBPersistentStore.initStore(MapDBPersistentStore.java:98)
    at io.moquette.spi.impl.ProtocolProcessorBootstrapper.init(ProtocolProcessorBootstrapper.java:77)
    at io.moquette.server.Server.startServer(Server.java:153)
    at io.moquette.server.Server.startServer(Server.java:135)
    at io.moquette.server.Server.startServer(Server.java:127)
    at io.moquette.server.Server.startServer(Server.java:94)
    at io.moquette.server.Server.main(Server.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: storage has invalid header
    ... 19 more

Code in MapDB project has changed considerably: there is NO StoreDirect.java file any longer.
Please help. Any ideas are appreciated!

**Comment by andsel** [comment]
Probably the MapDB file is corrupted,is not a fail from Moquette side,
probably the process was filled instead of clean shutdown and this
corrupeted the file. The only road I can think, is to drop that _mapdb_
files and restart the process.

 Andrea

**Comment by GeorgeMatveev** [comment]
Really funny things happen.
I believe done it before in Eclipse and it did not work.
I removed  mapdb stuff: rm moquette_store.mapdb*
and launched the project again and now it Works!
Thank you Andrea! Very nice project/code!

P.S. It seems choice of IDE makes a lot of difference.
