### ISSUE TITLE
ERROR NettyMQTTHandler  - Bad error in processing the message

### ISSUE THREAD

**Issue by paulmiu** [moquette-io/moquette#228]
I don't do anything special (only publish and subscribe to messages with QoS 0 and 2), but in the `moquette.log` the following error appears quite often:

```
0    [nioEventLoopGroup-3-2] ERROR NettyMQTTHandler  - Bad error in processing the message
java.lang.NullPointerException
    at io.moquette.spi.impl.ProtocolProcessor.processPubComp(ProtocolProcessor.java:668)
    at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:67)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:47)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)
```

I use the latest version (build from source) in embedded mode.
Has anyone else got this message?

**Comment by andsel** [comment]
Do you have an example to reproduce it?

**Comment by paulmiu** [comment]
No, that was the problem, because the error appeared sporadically.
I'm sorry, but I don't use moquette anymore. Had more luck with mosquitto.

Thanks anyway for all your effort!
(If you want, you can close this issue)

**Comment by andsel** [comment]
Closed because interest go to Moqsuitto

**Comment by sawyer7246** [comment]
Hi! I get this error today,any solution for this now？
Thanks！

**Comment by andsel** [comment]
You tried the master with 0.10-SNAPSHOT or the 0.9 version?
Do you have a test case to reproduce it?

**Comment by sawyer7246** [comment]
Yes,actually this happen in the 0.9 version.
Sorry, I don have any test case to reproduce it,however,this error appears quite often when I try to pub messages very fast(every 20ms) . that matters?
Thanks！

**Comment by andsel** [comment]
I'll try to reproduce and investigate. Thaks

**Comment by paulmiu** [comment]
@sawyer7246:
Which java version and operating system do you use?

**Comment by sawyer7246** [comment]
@mamiu jdk1.7.0_25 / windows 10 64bit

**Comment by paulmiu** [comment]
I used the same jdk on windows server 2012.

@andsel: maybe this information is helpfull to reproduce the error.

**Comment by amenak77** [comment]
Hi,
I'm Alberto; I'm part od Freedomotic team (www.freedomotic.com); same problem today and a test case so that you can reproduce the problem at will. Our aim is integrate souliss framework throught MQTT and node red, so we have, as part of test archtecture, an arduino MQTT node with a DHT11 sensor which sends to freedomotictesttopic1 topic, temperature values every 5 seconds. The point is that the MQTT broker is a plugin for freedomotic developed by Mauro with Moquette. After 278 messages divided by an interval of 5 seconds the plugin crashed.
![mqtt-moquette-err](https://user-images.githubusercontent.com/13914556/32544704-8b00d23e-c479-11e7-9e6e-22fde896659e.jpg)

**Comment by amenak77** [comment]
Here is the link to the pom.xml  https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/mqtt-broker/pom.xml  It seems Moquette library ver 0.10 5.6-SNAPSHOT; java RE 8 1.8.0-144-b01; OS win 10 64 bit. At the moment we think to take away from the marketplace the MQTT broker plugin and leave the MQTT client, but we hope that in a near future with a little library's debug and update, we can reintegrate it. Thank you very much, Alberto

**Comment by amenak77** [comment]
![mqtt-temp-ard](https://user-images.githubusercontent.com/13914556/32545172-208c5d04-c47b-11e7-9d8b-1f1888d9f048.jpg)
PD: if can be of help: here we can see the correct MQTT message published by arduino node (temp value) into main Freedomotic prompt window (verbose mode) via MQTT broker plugin

**Comment by amenak77** [comment]
19.00 Celsius degees.
@andsel thanks again if you can help us with this; maybe you italian too?

**Comment by andsel** [comment]
Hi @amenak77 yes I'm italian too.
It's just the an NPE of the previous issue, but the trace is little bit different as I can see.
Do you have a text form of the log (please enable also the messages logger so there is the complete sequence of messages, it's more verbose) so that I can investigate, or could you provide an executable reproducible test, in form of JUnit test case? It's little bit difficult to understand what could break from a couple of cmd screenshots.

**Comment by amenak77** [comment]
Hi @andsel glad to hear this and best compliments for your project. I'm sure this problem will be wipe out soon; hope to be of help. The log file is a bit long and I can attach image files only I guess. How can I send you the log? Thanks, Alberto

**Comment by mcicolella** [comment]
@andsel any update about this?

**Comment by andsel** [comment]
Hi @mcicolella  and @amenak77  I can't reproduce it, is available any detailed log of the issue and/or a unit/integration test to reproduce it?
Have you tried with version 0.11-SNAPSHOT?

**Comment by mcicolella** [comment]
Hi @andsel 
I updated our plugin to moquette v0.11 and it seems working well.
But @amenak77 is our "stress tester".

**Comment by andsel** [comment]
Great!! so I can close the Issue
