### ISSUE TITLE
What is causing -Bad error in processing the message java.lang.NullPointerException

### ISSUE THREAD

**Issue by asutoshg** [moquette-io/moquette#244]
===
 Hi,
After few hours  the broker starts printing this error and it keeps coming. what is the possible cause and how to avoid it.
Thanks
Asutosh

==
```
4835 [nioEventLoopGroup-3-4] INFO  ProtocolProcessor  - PUBLISH from clientID <pahomqttpublish_6822111420499807> on topic <Topic/TorpedoGPSTopic> with QoS MOST_ONE
4837 [nioEventLoopGroup-3-4] ERROR NettyMQTTHandler  - Bad error in processing the message
java.lang.NullPointerException
	at io.moquette.spi.impl.ProtocolProcessor.route2Subscribers(ProtocolProcessor.java:460)
	at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:310)
	at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:61)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:46)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
```

**Comment by andsel** [comment]
Hi I'm investigating why sometimes this happen. Could you re-test with latest sources enabling the MQTT message logger?
You just need to set to level INFO the messagelog logger in log4j.properties)
```
####################################
#   Message Logger Configuration   #
#####################################
log4j.appender.messagelog=org.apache.log4j.RollingFileAppender
log4j.appender.messagelog.Threshold=WARN
log4j.appender.messagelog.File=moquette_messages.log
log4j.appender.messagelog.MaxFileSize=100MB
log4j.appender.messagelog.MaxBackupIndex=1
log4j.appender.messagelog.layout=org.apache.log4j.PatternLayout
log4j.appender.messagelog.layout.ConversionPattern=%d{HH:mm:ss,SSS} [%t] %-5p %c{1} %L %x - %m%n

log4j.category.messageLogger=WARN, messagelog
```

**Comment by asutoshg** [comment]
Hi, I have just build the 0.9 src release and will report if I experience the issue again with the new version.
Thx.

**Comment by asutoshg** [comment]
Hi,
I would like to report that 0.9 is working for over 20 days without any issues.
Thanks

**Comment by andsel** [comment]
Thanks @asutoshg so I can close the issue.
In case of other bugs open a new one.
