### ISSUE TITLE
OSGi test fails

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#247]
The test on OSGi integration fails without finding moquette bundle.
This is the log from maven console:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.moquette.test.osgi.MoquetteOsgiTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Creating bundle watcher with scanner [org.ops4j.pax.swissbox.extender.BundleManifestScanner@a6ff882]...
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.apache.felix.framework]
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.exam]
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.exam.inject]
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.exam.extender.service]
[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [osgi.cmpn]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.logging.pax-logging-api]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.base]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.swissbox.core]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.swissbox.extender]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.swissbox.framework]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.swissbox.lifecycle]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.swissbox.tracker]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.apache.geronimo.specs.geronimo-atinject_1.0_spec]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.tipi.junit]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.tipi.hamcrest.core]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [org.ops4j.pax.exam.invoker.junit]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [null]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Scanning bundle [PAXEXAM-PROBE-a21e26b8-4593-4f02-902e-f2b62246c823]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Found resources [ManifestEntry{ key=PaxExam-Executable, value=PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8, }, ManifestEntry{ key=PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8, value=io.moquette.test.osgi.MoquetteOsgiTest;testCanFindOsgiBundle }]
org.ops4j.pax.exam.extender.service[org.ops4j.pax.exam.raw.extender.intern.Probe] : Test PaxExam-Executable to be in PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8,
org.ops4j.pax.exam.extender.service[org.ops4j.pax.exam.raw.extender.intern.Probe] : Test PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8 to be in PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8,
org.ops4j.pax.exam.extender.service[org.ops4j.pax.exam.raw.extender.intern.Probe] : Registering Service: org.ops4j.pax.exam.ProbeInvoker with Probe-Signature="PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8" and expression="io.moquette.test.osgi.MoquetteOsgiTest;testCanFindOsgiBundle"
org.ops4j.pax.exam.invoker.junit[org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner] : running testCanFindOsgiBundle in reactor
org.apache.felix.framework 32
org.ops4j.pax.exam 32
org.ops4j.pax.exam.inject 32
org.ops4j.pax.exam.extender.service 32
osgi.cmpn 32
org.ops4j.pax.logging.pax-logging-api 32
org.ops4j.base 32
org.ops4j.pax.swissbox.core 32
org.ops4j.pax.swissbox.extender 32
org.ops4j.pax.swissbox.framework 32
org.ops4j.pax.swissbox.lifecycle 32
org.ops4j.pax.swissbox.tracker 32
org.apache.geronimo.specs.geronimo-atinject_1.0_spec 32
org.ops4j.pax.tipi.junit 32
org.ops4j.pax.tipi.hamcrest.core 32
org.ops4j.pax.exam.invoker.junit 32
null 32
PAXEXAM-PROBE-a21e26b8-4593-4f02-902e-f2b62246c823 32
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [PAXEXAM-PROBE-a21e26b8-4593-4f02-902e-f2b62246c823]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Un-registering [ManifestEntry{ key=PaxExam-Executable, value=PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8, }, ManifestEntry{ key=PaxExam-670b1aa0-cac0-4530-8bbc-eb70533cdfb8, value=io.moquette.test.osgi.MoquetteOsgiTest;testCanFindOsgiBundle }]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.exam.raw.extender.intern.TestBundleObserver] : Unregistered testcase [org.ops4j.pax.exam.raw.extender.intern.Probe@217969ed.]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [null]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.exam.invoker.junit]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.tipi.hamcrest.core]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.tipi.junit]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.apache.geronimo.specs.geronimo-atinject_1.0_spec]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.swissbox.tracker]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.swissbox.lifecycle]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.swissbox.framework]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.swissbox.extender]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.swissbox.core]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.base]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling JULI Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.logging.pax-logging-api]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [osgi.cmpn]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.exam.extender.service]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.exam]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.apache.felix.framework]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.swissbox.extender.BundleWatcher] : Releasing bundle [org.ops4j.pax.exam.inject]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.942 sec <<< FAILURE!
testCanFindOsgiBundle(io.moquette.test.osgi.MoquetteOsgiTest)  Time elapsed: 0.767 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at io.moquette.test.osgi.MoquetteOsgiTest.testCanFindOsgiBundle(MoquetteOsgiTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:68)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

```

**Comment by kmhughes** [comment]
When I build, I see

org.apache.felix.framework 32
org.ops4j.pax.exam 32
org.ops4j.pax.exam.inject 32
org.ops4j.pax.exam.extender.service 32
osgi.cmpn 32
org.ops4j.pax.logging.pax-logging-api 32
org.ops4j.base 32
org.ops4j.pax.swissbox.core 32
org.ops4j.pax.swissbox.extender 32
org.ops4j.pax.swissbox.framework 32
org.ops4j.pax.swissbox.lifecycle 32
org.ops4j.pax.swissbox.tracker 32
org.apache.geronimo.specs.geronimo-atinject_1.0_spec 32
org.ops4j.pax.tipi.junit 32
org.ops4j.pax.tipi.hamcrest.core 32
org.ops4j.pax.exam.invoker.junit 32
io.moquette.broker 2

when it starts listing all the bundles.

Notice at the bottom you see 

null 32

in place of

io.moquette.broker 2

This makes it look like you have the OSGi header, but not a symbolic name for the header.

Can you do a build on your laptop and then place the broker jar somewhere where I can get it to look at it?

Cool, international debugging!

**Comment by kmhughes** [comment]
There is a section that looks like this in the logs:

    [echo] test classpath:    /home/keith/software/comm/mqtt/moquette/osgi_test/target/test-classes:/home/keith/software/comm/mqtt/moquette/osgi_test/target/classes:/home/keith/software/comm/mqtt/moquette/broker/target/moquette-broker-0.9-SNAPSHOT.jar:/home/keith/software/comm/mqtt/moquette/netty_parser/target/moquette-netty-parser-0.9-SNAPSHOT.jar:/home/keith/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/home/keith/.m2/repository/io/netty/netty-common/4.1.6.Final/netty-common-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-buffer/4.1.6.Final/netty-buffer-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-transport/4.1.6.Final/netty-transport-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-resolver/4.1.6.Final/netty-resolver-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-handler/4.1.6.Final/netty-handler-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-codec/4.1.6.Final/netty-codec-4.1.6.Final.jar:/home/keith/.m2/repository/io/netty/netty-codec-http/4.1.6.Final/netty-codec-http-4.1.6.Final.jar:/home/keith/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/keith/.m2/repository/org/mapdb/mapdb/1.0.8/mapdb-1.0.8.jar:/home/keith/.m2/repository/org/hdrhistogram/HdrHistogram/2.

Can you please include that in the issue?

**Comment by andsel** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Moquette - OSGi test 0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ moquette-osgi-test ---
[INFO] Deleting /home/andrea/workspace/moquette_github/osgi_test/target
[INFO] 
[INFO] --- depends-maven-plugin:1.2:generate-depends-file (generate-depends-file) @ moquette-osgi-test ---
[INFO] Created: /home/andrea/workspace/moquette_github/osgi_test/target/classes/META-INF/maven/dependencies.properties
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ moquette-osgi-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/andrea/workspace/moquette_github/osgi_test/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ moquette-osgi-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (compile) @ moquette-osgi-test ---
[INFO] Executing tasks

main:
     [echo] compile classpath: /home/andrea/workspace/moquette_github/osgi_test/target/classes
     [echo] runtime classpath: /home/andrea/workspace/moquette_github/osgi_test/target/classes
     [echo] test classpath:    /home/andrea/workspace/moquette_github/osgi_test/target/test-classes:/home/andrea/workspace/moquette_github/osgi_test/target/classes:/home/andrea/workspace/moquette_github/broker/target/moquette-broker-0.9-SNAPSHOT.jar:/home/andrea/workspace/moquette_github/netty_parser/target/moquette-netty-parser-0.9-SNAPSHOT.jar:/home/andrea/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/home/andrea/.m2/repository/io/netty/netty-common/4.1.6.Final/netty-common-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-buffer/4.1.6.Final/netty-buffer-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-transport/4.1.6.Final/netty-transport-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-resolver/4.1.6.Final/netty-resolver-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-handler/4.1.6.Final/netty-handler-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-codec/4.1.6.Final/netty-codec-4.1.6.Final.jar:/home/andrea/.m2/repository/io/netty/netty-codec-http/4.1.6.Final/netty-codec-http-4.1.6.Final.jar:/home/andrea/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/andrea/.m2/repository/org/mapdb/mapdb/1.0.8/mapdb-1.0.8.jar:/home/andrea/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/andrea/.m2/repository/com/hazelcast/hazelcast/3.5.4/hazelcast-3.5.4.jar:/home/andrea/.m2/repository/org/ops4j/pax/exam/pax-exam-container-native/4.6.0/pax-exam-container-native-4.6.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/exam/pax-exam/4.6.0/pax-exam-4.6.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-store/1.5.0/ops4j-base-store-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-io/1.5.0/ops4j-base-io-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-util-property/1.5.0/ops4j-base-util-property-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/exam/pax-exam-spi/4.6.0/pax-exam-spi-4.6.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-spi/1.5.0/ops4j-base-spi-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/tinybundles/tinybundles/2.1.1/tinybundles-2.1.1.jar:/home/andrea/.m2/repository/biz/aQute/bnd/bndlib/2.4.0/bndlib-2.4.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-core/1.8.1/pax-swissbox-core-1.8.1.jar:/home/andrea/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.8.1/pax-swissbox-lifecycle-1.8.1.jar:/home/andrea/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-tracker/1.8.1/pax-swissbox-tracker-1.8.1.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-lang/1.5.0/ops4j-base-lang-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-net/1.5.0/ops4j-base-net-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-monitors/1.5.0/ops4j-base-monitors-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/url/pax-url-link/2.4.1/pax-url-link-2.4.1.jar:/home/andrea/.m2/repository/org/ops4j/pax/url/pax-url-classpath/2.4.1/pax-url-classpath-2.4.1.jar:/home/andrea/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-optional-jcl/1.8.1/pax-swissbox-optional-jcl-1.8.1.jar:/home/andrea/.m2/repository/org/ops4j/pax/exam/pax-exam-junit4/4.6.0/pax-exam-junit4-4.6.0.jar:/home/andrea/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/andrea/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/andrea/.m2/repository/org/ops4j/pax/exam/pax-exam-link-mvn/4.6.0/pax-exam-link-mvn-4.6.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/url/pax-url-aether/1.4.0/pax-url-aether-1.4.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/url/pax-url-commons/1.4.0/pax-url-commons-1.4.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-property/1.5.0/pax-swissbox-property-1.5.0.jar:/home/andrea/.m2/repository/org/ops4j/pax/url/pax-url-maven-commons/1.4.0/pax-url-maven-commons-1.4.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-util-xml/1.3.0/ops4j-base-util-xml-1.3.0.jar:/home/andrea/.m2/repository/org/ops4j/base/ops4j-base-util-collections/1.3.0/ops4j-base-util-collections-1.3.0.jar:/home/andrea/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar:/home/andrea/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar:/home/andrea/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar:/home/andrea/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar:/home/andrea/.m2/repository/org/sonatype/aether/aether-connector-wagon/1.13.1/aether-connector-wagon-1.13.1.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.jar:/home/andrea/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/2.2.3/sisu-inject-plexus-2.2.3.jar:/home/andrea/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.2.3/sisu-inject-bean-2.2.3.jar:/home/andrea/.m2/repository/org/sonatype/sisu/sisu-guice/3.0.3/sisu-guice-3.0.3-no_aop.jar:/home/andrea/.m2/repository/org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.jar:/home/andrea/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar:/home/andrea/.m2/repository/org/apache/maven/maven-model-builder/3.0.4/maven-model-builder-3.0.4.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar:/home/andrea/.m2/repository/org/apache/maven/maven-repository-metadata/3.0.4/maven-repository-metadata-3.0.4.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar:/home/andrea/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-7/wagon-provider-api-1.0-beta-7.jar:/home/andrea/.m2/repository/org/apache/maven/wagon/wagon-file/1.0-beta-7/wagon-file-1.0-beta-7.jar:/home/andrea/.m2/repository/org/apache/maven/wagon/wagon-http-lightweight/1.0-beta-7/wagon-http-lightweight-1.0-beta-7.jar:/home/andrea/.m2/repository/org/apache/maven/wagon/wagon-http-shared/1.0-beta-7/wagon-http-shared-1.0-beta-7.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.jar:/home/andrea/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar:/home/andrea/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar:/home/andrea/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/home/andrea/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/home/andrea/.m2/repository/org/apache/felix/org.apache.felix.framework/5.0.0/org.apache.felix.framework-5.0.0.jar:/home/andrea/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
     [echo] plugin classpath:  /home/andrea/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7/maven-antrun-plugin-1.7.jar:/home/andrea/.m2/repository/org/apache/maven/maven-plugin-api/2.0.11/maven-plugin-api-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-project/2.0.11/maven-project-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-profile/2.0.11/maven-profile-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-artifact-manager/2.0.11/maven-artifact-manager-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.11/maven-repository-metadata-2.0.11.jar:/home/andrea/.m2/repository/org/apache/maven/maven-plugin-registry/2.0.11/maven-plugin-registry-2.0.11.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar:/home/andrea/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar:/home/andrea/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar:/home/andrea/.m2/repository/org/apache/maven/maven-artifact/2.0.11/maven-artifact-2.0.11.jar:/home/andrea/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar:/home/andrea/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar:/home/andrea/.m2/repository/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ moquette-osgi-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/andrea/workspace/moquette_github/osgi_test/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ moquette-osgi-test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/andrea/workspace/moquette_github/osgi_test/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ moquette-osgi-test ---
[INFO] Surefire report directory: /home/andrea/workspace/moquette_github/osgi_test/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.moquette.test.osgi.MoquetteOsgiTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

```

**Comment by andsel** [comment]
Manifest of my moquette-broker jar
```
Manifest-Version: 1.0
Bundle-Description: Moquette lightweight MQTT Broker
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt, http:/
 /www.eclipse.org/org/documents/epl-v10.php
Bundle-SymbolicName: io.moquette.broker
Archiver-Version: Plexus Archiver
Built-By: andrea
Bnd-LastModified: 1483197403497
Bundle-ManifestVersion: 2
Import-Package: com.hazelcast.config;version="[3.5,4)",com.hazelcast.c
 ore;version="[3.5,4)",io.moquette.parser.netty;version="[0.9,1)",io.m
 oquette.parser.proto;version="[0.9,1)",io.moquette.parser.proto.messa
 ges;version="[0.9,1)",io.moquette.server.config,io.moquette.server.ne
 tty.metrics,io.moquette.spi.security,io.netty.bootstrap;version="[4.1
 ,5)",io.netty.buffer;version="[4.1,5)",io.netty.channel;version="[4.1
 ,5)",io.netty.channel.nio;version="[4.1,5)",io.netty.channel.socket;v
 ersion="[4.1,5)",io.netty.channel.socket.nio;version="[4.1,5)",io.net
 ty.handler.codec;version="[4.1,5)",io.netty.handler.codec.http;versio
 n="[4.1,5)",io.netty.handler.codec.http.websocketx;version="[4.1,5)",
 io.netty.handler.ssl;version="[4.1,5)",io.netty.handler.timeout;versi
 on="[4.1,5)",io.netty.util;version="[4.1,5)",io.netty.util.concurrent
 ;version="[4.1,5)",javax.net.ssl,org.apache.commons.codec.binary;vers
 ion="[1.10,2)",org.apache.commons.codec.digest;version="[1.10,2)",org
 .mapdb;version="[1.0,2)",org.slf4j;version="[1.7,2)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Tool: Bnd-3.2.0.201605172007
Export-Package: io.moquette.spi;uses:="io.moquette.parser.proto.messag
 es";version="0.9.0",io.moquette.spi.persistence;uses:="io.moquette.se
 rver.config,io.moquette.spi";version="0.9.0",io.moquette.spi.security
 ;uses:="javax.net.ssl";version="0.9.0",io.moquette;version="0.9.0",io
 .moquette.interception;uses:="io.moquette.interception.messages,io.mo
 quette.parser.proto.messages,io.moquette.server";version="0.9.0",io.m
 oquette.interception.messages;uses:="io.moquette.parser.proto.message
 s,io.moquette.spi";version="0.9.0",io.moquette.server;uses:="com.haze
 lcast.core,io.moquette.interception,io.moquette.parser.proto.messages
 ,io.moquette.server.config,io.moquette.spi.security,io.netty.channel"
 ;version="0.9.0",io.moquette.server.config;version="0.9.0",io.moquett
 e.server.netty;uses:="io.moquette.server,io.moquette.server.config,io
 .moquette.spi.security,io.netty.channel,io.netty.util";version="0.9.0
 ",io.moquette.server.netty.metrics;uses:="io.netty.channel";version="
 0.9.0"
Bundle-Name: Moquette - broker
Bundle-Version: 0.9.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_60

```

**Comment by kmhughes** [comment]
This is odd. All of the OSGi headers are correct in your broker jar.

**Comment by kmhughes** [comment]
OK, I will dig into this and see if I can find anything. Will let you know ASAP.

**Comment by andsel** [comment]
My laptop environment:
Ubuntu 15.10
Apache Maven 3.3.3
Java version: 1.8.0_60

**Comment by windbender** [comment]
same problem here:

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.837 sec <<< FAILURE!
testCanFindOsgiBundle(io.moquette.test.osgi.MoquetteOsgiTest)  Time elapsed: 5.538 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at io.moquette.test.osgi.MoquetteOsgiTest.testCanFindOsgiBundle(MoquetteOsgiTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)


OS X 10.11.6
java version "1.8.0_05"
Apache Maven 3.3.9

**Comment by andsel** [comment]
Closed because Moquette doesn't support anymore OSGi
