### ISSUE TITLE
java.lang.UnsupportedOperationException: direct buffer at io.netty.buffer.PooledUnsafeDirectByteBuf.array

### ISSUE THREAD

**Issue by mcicolella** [moquette-io/moquette#341]
Hi all,
I just updated our plugin to moquette 0.10 but I have a problem when publishing on a topic.

The following exception is raised

`
2017-07-25 18:41:22,921 INFO  [nioEventLoopGroup-3-1] - C->B PUBLISH <emmecilab183511868> to topics </prova>
2017-07-25 18:41:22,922 INFO  [nioEventLoopGroup-3-1] - Processing PUBLISH message. CId=emmecilab183511868, topic=/prova, messageId=-1, qos=AT_MOST_ONCE
Exception in thread "pool-3-thread-1" java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:343)
	at io.netty.buffer.AbstractPooledDerivedByteBuf.array(AbstractPooledDerivedByteBuf.java:118)
	at com.freedomotic.plugins.devices.mqttbroker.MqttBroker$PublisherListener.onPublish(MqttBroker.java:167)
	at io.moquette.spi.impl.BrokerInterceptor.lambda$notifyTopicPublished$4(BrokerInterceptor.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

I'm using mqtt-spy fot testing.

I noticed another error related to session at plugin startup
`
2017-07-25 18:39:58,089 INFO  [nioEventLoopGroup-3-1] - C->B CONNECT <null>
2017-07-25 18:39:58,089 INFO  [nioEventLoopGroup-3-1] - Processing CONNECT message. CId=emmecilab183511868, username=null
2017-07-25 18:39:58,102 INFO  [nioEventLoopGroup-3-1] - Configuring connection. CId=emmecilab183511868
2017-07-25 18:39:58,102 INFO  [nioEventLoopGroup-3-1] - Sending connect ACK. CId=emmecilab183511868
2017-07-25 18:39:58,102 ERROR [nioEventLoopGroup-3-1] - Can't find the session for client <emmecilab183511868>
2017-07-25 18:39:58,103 INFO  [nioEventLoopGroup-3-1] - C<-B CONNACK <emmecilab183511868>
2017-07-25 18:39:58,110 INFO  [nioEventLoopGroup-3-1] - The connect ACK has been sent. CId=emmecilab183511868
`

My code is [here](https://github.com/mcicolella/freedomotic/tree/mqtt/plugins/devices/mqtt-broker).
What is wrong?

**Comment by andsel** [comment]
The problem is in freedomotic code, https://github.com/mcicolella/freedomotic/blob/mqtt/plugins/devices/mqtt-broker/src/main/java/com/freedomotic/plugins/devices/mqttbroker/MqttBroker.java#L167 array() is a ByteBuf operation that is not supported by all types of buffers (for example direct or composite doesn't provide it) so you have to read the ByteBuf content with any form of ByteBuf.getBytes() methods.

**Comment by mrwhy-orig** [comment]
@andsel i'm facing the exact same problem with the embedded example code. Maybe it should be updated.
