### ISSUE TITLE
java.lang.NullPointerException at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch

### ISSUE THREAD

**Issue by rongwei84n** [moquette-io/moquette#361]
problem: 
```
java.lang.NullPointerException 
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch(CTrieSubscriptionDirectory.java:180)
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.match(CTrieSubscriptionDirectory.java:148)
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.matches(CTrieSubscriptionDirectory.java:134)
        at io.moquette.spi.impl.MessagesPublisher.publish2Subscribers(MessagesPublisher.java:73)
        at io.moquette.spi.impl.Qos0PublishHandler.receivedPublishQos0(Qos0PublishHandler.java:59)
        at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:503)
        at io.moquette.spi.impl.MqttUtil.testPublishToMultipleSubscribers(MqttUtil.java:76)
        at io.moquette.spi.impl.MqttUtil.publishToMultiSubs(MqttUtil.java:62)
        at org.phihome.topics.CommandPipeReader.passThroughEvent(CommandPipeReader.java:89)
        at org.phihome.topics.CommandPipeReader.access$000(CommandPipeReader.java:19)
        at org.phihome.topics.CommandPipeReader$1.run(CommandPipeReader.java:54)
        at java.lang.Thread.run(Thread.java:748)
```
reason:
1. if user nerver subscribe a topic after it connect to the mqtt server, then unsubscribe a topic, such as 'root'.
2. then subscribe a other topic such as 'a/b/c'
3. publish a topic 'a'

you will get this Exception.

fix:
below is a patch to solve this problem.

[a.patch.zip](https://github.com/andsel/moquette/files/1298544/a.patch.zip)

**Comment by mwilliford** [comment]
@rongwei84n This might be fixed now in 95a8b313e5b410155f24849600327679387acb6f
Please let us know.
