### ISSUE TITLE
Maven build is stuck

### ISSUE THREAD

**Issue by mispecto** [moquette-io/moquette#37]
I'm running: `mvn clean install`

Maven version: 3.3
JDL: OpenJDK 7

And the build process is always stuck at:

```
13:40:03,788 [pool-57-thread-1] ERROR SimpleMessaging onEvent 173  - Serious error processing the message org.eclipse.moquette.proto.messages.DisconnectMessage@5dd3c8ce for session [clientID: Publisher]org.eclipse.moquette.server.netty.NettyChannel@64953d6b
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:167)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:57)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Could not instantiate class
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:526)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1416)
    at org.mapdb.SerializerBase.deserializeHashSet(SerializerBase.java:1678)
    at org.mapdb.SerializerBase.access$600(SerializerBase.java:30)
    at org.mapdb.SerializerBase$49.deserialize(SerializerBase.java:779)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1414)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1402)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:156)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:129)
    at org.mapdb.Store.deserialize(Store.java:296)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:600)
    at org.mapdb.Store.get(Store.java:146)
    at org.mapdb.HTreeMap.removeInternal(HTreeMap.java:1055)
    at org.mapdb.HTreeMap.remove(HTreeMap.java:1010)
    at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.wipeSubscriptions(MapDBPersistentStore.java:249)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.cleanSession(ProtocolProcessor.java:280)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processDisconnect(ProtocolProcessor.java:530)
    ... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:492)
    ... 26 more
May 14, 2015 1:40:48 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
SEVERE: Exception processing: 10 org.eclipse.moquette.spi.impl.ValueEvent@5454d285
java.lang.RuntimeException: Could not instantiate class
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:526)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1416)
    at org.mapdb.SerializerBase.deserializeHashSet(SerializerBase.java:1678)
    at org.mapdb.SerializerBase.access$600(SerializerBase.java:30)
    at org.mapdb.SerializerBase$49.deserialize(SerializerBase.java:779)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1414)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1402)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:156)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:129)
    at org.mapdb.Store.deserialize(Store.java:296)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:600)
    at org.mapdb.Store.get(Store.java:146)
    at org.mapdb.HTreeMap.putInner(HTreeMap.java:893)
    at org.mapdb.HTreeMap.put(HTreeMap.java:849)
    at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.updateSubscriptions(MapDBPersistentStore.java:255)
    at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.deactivate(SubscriptionsStore.java:180)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:557)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:158)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:57)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:492)
    ... 22 more

Exception in thread "pool-57-thread-1" java.lang.RuntimeException: java.lang.RuntimeException: Could not instantiate class
    at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not instantiate class
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:526)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1416)
    at org.mapdb.SerializerBase.deserializeHashSet(SerializerBase.java:1678)
    at org.mapdb.SerializerBase.access$600(SerializerBase.java:30)
    at org.mapdb.SerializerBase$49.deserialize(SerializerBase.java:779)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1414)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1402)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:156)
    at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:129)
    at org.mapdb.Store.deserialize(Store.java:296)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:600)
    at org.mapdb.Store.get(Store.java:146)
    at org.mapdb.HTreeMap.putInner(HTreeMap.java:893)
    at org.mapdb.HTreeMap.put(HTreeMap.java:849)
    at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.updateSubscriptions(MapDBPersistentStore.java:255)
    at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.deactivate(SubscriptionsStore.java:180)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:557)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:158)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:57)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    ... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:492)
    ... 22 more
```

**Comment by andsel** [comment]
Hi this is due to bug in MapDB library, rollbacked to 2.0-alpha2 and fixed.
