### ISSUE TITLE
client can't reconnect to the broker once exception happened inner processSubscribe()

### ISSUE THREAD

**Issue by fjcyue** [moquette-io/moquette#388]
Hi andsel，
  we found a device that continuously failed when connecting to the broker，this device using paho mqtt client，and always failed to subscribe to some topic，then disconnect and try to reconnect again and again.
 we trace the log, then found something like this:

> 2018-02-07 00:03:43.309 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Processing CONNECT message. CId=00000123, username=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Configuring connection. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Configuring MQTT last will and testament CId=00000123, willQos=AT_MOST_ONCE, willTopic=/s/cli, willRetain=false
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - MQTT last will and testament has been configured. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Sending connect ACK. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Cleaning session. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  messageLogger - C<-B CONNACK <00000123>
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - The connect ACK has been sent. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Cleaning session. CId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.persistence.MemorySessionStore - Removing stored messages with QoS 1 and 2. ClientId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.persistence.MemorySessionStore - Wiping existing subscriptions. ClientId=00000123
> 2018-02-07 00:03:43.311 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - CONNECT message processed CId=00000123, username=00000123
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  messageLogger - C->B SUBSCRIBE <00000123> to topics [MqttTopicSubscription[topicFilter=/d/cli, qualityOfService=AT_LEAST_ONCE]]
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Processing SUBSCRIBE message. CId=00000123, messageId=1
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Client will be subscribed to the topic CId=00000123, username=00000123, messageId=1, topic=/d/cli
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Creating and storing subscriptions CId=00000123, messageId=1, topics=[MqttTopicSubscription[topicFilter=/d/cli, qualityOfService=AT_LEAST_ONCE]]
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  io.moquette.spi.ClientSession - Adding new subscription. CId=00000123, topics=/d/cli, qos=AT_LEAST_ONCE
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Sending SUBACK response CId=00000123, messageId=1
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  messageLogger - C<-B SUBACK <00000123> packetID <1>, grantedQoses [1]
> 2018-02-07 00:03:48.196 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Retrieving retained messages CId=00000123, topics=/d/cli
> 2018-02-07 00:04:48.193 [nioEventLoopGroup-3-3] INFO  messageLogger - C->B PINGREQ <00000123>
> 2018-02-07 00:04:48.193 [nioEventLoopGroup-3-3] INFO  messageLogger - C<-B PINGRESP <00000123>
> 2018-02-07 00:05:30.659 [nioEventLoopGroup-3-3] INFO  messageLogger - C->B SUBSCRIBE <00000123> to topics [MqttTopicSubscription[topicFilter=/d/cli/00000123, qualityOfService=AT_LEAST_ONCE]]
> 2018-02-07 00:05:30.659 [nioEventLoopGroup-3-3] INFO  i.m.spi.impl.ProtocolProcessor - Processing SUBSCRIBE message. CId=00000123, messageId=2
> 2018-02-07 00:05:30.659 [nioEventLoopGroup-3-3] WARN  i.m.spi.impl.ProtocolProcessor - Client sent another SUBSCRIBE message while this one was being processed CId=00000123, messageId=2

it's always failed at the second subscribe, we review the `ProtocolProcessor#processSubscribe()`,  thought that there's something wrong in the past, cause the `SubscriptionState` left in the `subscriptionInCourse`  map and abandon the later reconnect.

So sorry we can't find the original exception of the processSubscribe(). 
But we thought SubscriptionState should be cleared at any time by surrounding the later codes after putIfAbsent() with try...finally. Or,  it should be cleared when processing connectionLost event with other similar resources?

**Comment by fjcyue** [comment]
we found the root cause，seems that the CTrie not implements well:

> 2018-01-19 19:27:30.748 [nioEventLoopGroup-3-3] ERROR i.m.server.netty.NettyMQTTHandler - Exception was caught while processing MQTT message, null
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_111]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_111]
        at io.moquette.spi.impl.subscriptions.CNode.anyChildrenMatch(CNode.java:43) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.insert(CTrieSubscriptionDirectory.java:202) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.insert(CTrieSubscriptionDirectory.java:205) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.insert(CTrieSubscriptionDirectory.java:205) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.insert(CTrieSubscriptionDirectory.java:205) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.add(CTrieSubscriptionDirectory.java:196) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.spi.impl.ProtocolProcessor.processSubscribe(ProtocolProcessor.java:804) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
        at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:50) ~[moquette-broker-0.11-SNAPSHOT.jar:na]

**Comment by fjcyue** [comment]
this issue is the same with #316 with different cause，and PR #368 is not enough.

**Comment by fjcyue** [comment]
We also found something similar like this:

> java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_111]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_111]
	at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch(CTrieSubscriptionDirectory.java:186) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
	at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch(CTrieSubscriptionDirectory.java:187) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
	at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch(CTrieSubscriptionDirectory.java:187) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
	at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.recursiveMatch(CTrieSubscriptionDirectory.java:187) ~[moquette-broker-0.11-SNAPSHOT.jar:na]
	at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.match(CTrieSubscriptionDirectory.java:148) ~[moquette-broker-0.11-SNAPSHOT.jar:na]


It seems that `CNode#copy()` doesn't implement correctly, it did a shallow copy, but the inner `children` list and `subscriptions` should also do a shallow copy too.

**Comment by fjcyue** [comment]
ok，@mwilliford fix the shallow copy in PR #365 ，i will do the left，modify the `processSubscribe()` to prevent continuously failure if any error happened inner it.

**Comment by andsel** [comment]
Hi @fjcyue this issue is still valid after integration of deepCopy from PR #365? If not it could be closed

**Comment by fjcyue** [comment]
@andsel PR #365 is not enough, it fix the root cause.  But if  any other  error happened in processing subscribe msg，this client may result in the state that connected but never subscribed even if the client resend the subscribe message. the new subscribe msg simply dropped for incorrect `currentStatus` value.
so i modified the  `processSubscribe()` to correct the state machine
