### ISSUE TITLE
publish2Subscribers problem

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#4]
Steps that reproduce the problem:
1. start broker with a clean system (=no db)
2a. connect a subscriber
2b. connect a publisher and publish some messages
3b. broker works well
4. kill broker
5. kill subscribers
6. restart broker
7. connect and publish a message
8. broker goes wrong because it tries to submit to old subscribers 
   (see attached logs)

MOQUETTE.LOG
Maybe I didn't understand the logic behind the code but I think that when broker is started the old subscriptions need to be deleted from the db.

I'm using Moquette v0.7 on Windows 8.1 (my dev environment)

0    [main] DEBUG SubscriptionsStore  - init invoked
6    [main] DEBUG MapDBPersistentStore  - retrieveAllSubscriptions returning subs []
7    [main] DEBUG SubscriptionsStore  - Reloading all stored subscriptions...subscription tree before 

7    [main] DEBUG SubscriptionsStore  - Finished loading. Subscription tree after 

8    [main] INFO  FileAuthenticator  - Loading password file: C:\bin\eclipse43.workspaces\spazio1\moquette-mqtt-broker\src\config\password_file.conf
8    [main] DEBUG ProtocolProcessor  - subscription tree on init 

531  [main] INFO  NettyAcceptor  - Server binded
535  [main] INFO  NettyAcceptor  - Server binded
536  [main] INFO  NettyAcceptor  - SSL is disabled
10187 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type CONNECT
10187 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event ProtocolEvent wrapping CONNECT
10188 [pool-1-thread-1] INFO  SimpleMessaging  - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping CONNECT
10188 [pool-1-thread-1] DEBUG ProtocolProcessor  - processConnect for client mosqsub/24676-DVL
10189 [pool-1-thread-1] DEBUG ProtocolProcessor  - Connect with keepAlive 60 s
10191 [pool-1-thread-1] DEBUG SubscriptionsStore  - Activating subscriptions for clientID <mosqsub/24676-DVL>
10283 [pool-1-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <mosqsub/24676-DVL>
10317 [pool-1-thread-1] DEBUG ProtocolProcessor  - processConnect sent OK ConnAck
10319 [pool-1-thread-1] WARN  ProtocolProcessor  - Connected client ID <mosqsub/24676-DVL> with clean session true
10320 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID mosqsub/24676-DVL
10321 [pool-1-thread-1] DEBUG MapDBPersistentStore  - addNewSubscription invoked with subscription [filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true] for client mosqsub/24676-DVL
10321 [pool-1-thread-1] DEBUG MapDBPersistentStore  - clientID mosqsub/24676-DVL is a newcome, creating it's subscriptions set
10322 [pool-1-thread-1] DEBUG MapDBPersistentStore  - updating clientID mosqsub/24676-DVL subscriptions set with new subscription
10331 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type SUBSCRIBE
10331 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event ProtocolEvent wrapping SUBSCRIBE
10344 [pool-1-thread-1] DEBUG MapDBPersistentStore  - clientID mosqsub/24676-DVL subscriptions set now is [[filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]]
10384 [pool-1-thread-1] INFO  SimpleMessaging  - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping SUBSCRIBE
10384 [pool-1-thread-1] DEBUG ProtocolProcessor  - processSubscribe invoked from client mosqsub/24676-DVL with msgID 1
10385 [pool-1-thread-1] INFO  ProtocolProcessor  - <mosqsub/24676-DVL> subscribed to topic 78:25:44:7E:E9:A0/D with QoS 0 - MOST_ONE
10385 [pool-1-thread-1] DEBUG MapDBPersistentStore  - addNewSubscription invoked with subscription [filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true] for client mosqsub/24676-DVL
10385 [pool-1-thread-1] DEBUG MapDBPersistentStore  - updating clientID mosqsub/24676-DVL subscriptions set with new subscription
10386 [pool-1-thread-1] DEBUG MapDBPersistentStore  - clientID mosqsub/24676-DVL subscriptions set now is [[filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true], [filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]]
10422 [pool-1-thread-1] DEBUG MapDBPersistentStore  - searchMatching scanning all retained messages, presents are 0
10422 [pool-1-thread-1] DEBUG ProtocolProcessor  - replying with SubAck to MSG ID 1
0    [main] DEBUG SubscriptionsStore  - init invoked
13223 [main] DEBUG MapDBPersistentStore  - retrieveAllSubscriptions returning subs [[filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true], [filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]]
15744 [main] DEBUG SubscriptionsStore  - Reloading all stored subscriptions...subscription tree before 

33059 [main] DEBUG SubscriptionsStore  - Re-subscribing mosqsub/24676-DVL to topic 78:25:44:7E:E9:A0/D
58676 [main] DEBUG SubscriptionsStore  - Re-subscribing mosqsub/24676-DVL to topic 
66856 [main] DEBUG SubscriptionsStore  - Finished loading. Subscription tree after 
78:25:44:7E:E9:A0
D[filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]
[filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]

87979 [main] INFO  FileAuthenticator  - Loading password file: C:\bin\eclipse43.workspaces\spazio1\moquette-mqtt-broker\src\config\password_file.conf
87980 [main] DEBUG ProtocolProcessor  - subscription tree on init 
78:25:44:7E:E9:A0
D[filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]
[filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]

88685 [main] INFO  NettyAcceptor  - Server binded
88687 [main] INFO  NettyAcceptor  - Server binded
88689 [main] INFO  NettyAcceptor  - SSL is disabled
95949 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type CONNECT
95950 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event ProtocolEvent wrapping CONNECT
95951 [pool-1-thread-1] INFO  SimpleMessaging  - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping CONNECT
95951 [pool-1-thread-1] DEBUG ProtocolProcessor  - processConnect for client mosqpub/27720-DVL
95952 [pool-1-thread-1] DEBUG ProtocolProcessor  - Connect with keepAlive 60 s
95955 [pool-1-thread-1] DEBUG SubscriptionsStore  - Activating subscriptions for clientID <mosqpub/27720-DVL>
125014 [pool-1-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <mosqpub/27720-DVL>
125072 [pool-1-thread-1] DEBUG ProtocolProcessor  - processConnect sent OK ConnAck
125098 [pool-1-thread-1] WARN  ProtocolProcessor  - Connected client ID <mosqpub/27720-DVL> with clean session true
125098 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID mosqpub/27720-DVL
125098 [pool-1-thread-1] DEBUG MapDBPersistentStore  - addNewSubscription invoked with subscription [filter:, cliID: mosqpub/27720-DVL, qos: MOST_ONE, active: true] for client mosqpub/27720-DVL
125098 [pool-1-thread-1] DEBUG MapDBPersistentStore  - clientID mosqpub/27720-DVL is a newcome, creating it's subscriptions set
125099 [pool-1-thread-1] DEBUG MapDBPersistentStore  - updating clientID mosqpub/27720-DVL subscriptions set with new subscription
125100 [nioEventLoopGroup-3-1] INFO  PublishDecoder  - decode invoked with buffer UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 833, cap: 1024)
125100 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PUBLISH
125100 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event ProtocolEvent wrapping PUBLISH
125100 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type DISCONNECT
125100 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event ProtocolEvent wrapping DISCONNECT
125103 [nioEventLoopGroup-3-1] DEBUG SimpleMessaging  - disruptorPublish publishing event org.dna.mqtt.moquette.messaging.spi.impl.events.LostConnectionEvent@ff6c19
125115 [pool-1-thread-1] DEBUG MapDBPersistentStore  - clientID mosqpub/27720-DVL subscriptions set now is [[filter:, cliID: mosqpub/27720-DVL, qos: MOST_ONE, active: true]]
125153 [pool-1-thread-1] INFO  SimpleMessaging  - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping PUBLISH
125153 [pool-1-thread-1] TRACE ProtocolProcessor  - PUB --PUBLISH--> SRV processPublish invoked with org.dna.mqtt.moquette.proto.messages.PublishMessage@15dcd1d
125153 [pool-1-thread-1] INFO  ProtocolProcessor  - Publish recieved from clientID <mosqpub/27720-DVL> on topic 78:25:44:7E:E9:A0/D with QoS MOST_ONE
125153 [pool-1-thread-1] DEBUG ProtocolProcessor  - publish2Subscribers republishing to existing subscribers that matches the topic 78:25:44:7E:E9:A0/D
125155 [pool-1-thread-1] DEBUG ProtocolProcessor  - content <{XYZ}>
125155 [pool-1-thread-1] DEBUG ProtocolProcessor  - subscription tree 
78:25:44:7E:E9:A0
D[filter:78:25:44:7E:E9:A0/D, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]
[filter:, cliID: mosqsub/24676-DVL, qos: MOST_ONE, active: true]

133913 [pool-1-thread-1] DEBUG ProtocolProcessor  - Broker republishing to client <mosqsub/24676-DVL> topic 78:25:44:7E:E9:A0/D qos <MOST_ONE>, active true
145081 [pool-1-thread-1] DEBUG ProtocolProcessor  - sendPublish invoked clientId <mosqsub/24676-DVL> on topic 78:25:44:7E:E9:A0/D QoS MOST_ONE retained false messageID 1
145081 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <mosqsub/24676-DVL> on topic 78:25:44:7E:E9:A0/D
145081 [pool-1-thread-1] DEBUG ProtocolProcessor  - content <{XYZ}>
145082 [pool-1-thread-1] DEBUG ProtocolProcessor  - clientIDs are {mosqpub/27720-DVL=ConnectionDescriptor{m_clientID=mosqpub/27720-DVL, m_cleanSession=true}}

Server started, version 0.7-SNAPSHOT
125098 [pool-1-thread-1] WARN  ProtocolProcessor  - Connected client ID <mosqpub/27720-DVL> with clean session true
dic 02, 2014 8:17:45 PM com.lmax.disruptor.FatalExceptionHandler handleEventException
SEVERE: Exception processing: 1 org.dna.mqtt.moquette.messaging.spi.impl.ValueEvent@c625e1
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.dna.mqtt.moquette.messaging.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:156)
    at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.dna.mqtt.moquette.messaging.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <mosqsub/24676-DVL> in cache <{mosqpub/27720-DVL=ConnectionDescriptor{m_clientID=mosqpub/27720-DVL, m_cleanSession=true}}>
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:410)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:386)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.publish2Subscribers(ProtocolProcessor.java:359)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:306)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:281)
    ... 11 more

Exception in thread "pool-1-thread-1" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.dna.mqtt.moquette.messaging.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:156)
    at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:113)
    ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.dna.mqtt.moquette.messaging.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <mosqsub/24676-DVL> in cache <{mosqpub/27720-DVL=ConnectionDescriptor{m_clientID=mosqpub/27720-DVL, m_cleanSession=true}}>
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:410)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:386)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.publish2Subscribers(ProtocolProcessor.java:359)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:306)
    at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:281)
    ... 11 more

Reporter: diegovis
Original: https://code.google.com/p/moquette-mqtt/issues/detail?id=54

**Comment by andsel** [comment]
The issue has been verified with integration scripts issue4_publish2Subscribers.groovy (for steps 1-3) and trivialPublish.groovy for step 7, starting and restarting the serve by hand, but the issue is not reproducible with 0.7 snapshot

**Comment by wns349** [comment]
I get the same error on 0.7 snapshot. Any word of advice on this, please? 

I'm currently using mqttv3-1.0.2.jar, using Eclipse IDE on Windows 7. 

The way to reproduce the error is the same as mentioned in the original post. The broker server is killed (by clicking on the red stop button on Eclipse) and restarted back after all the client connections are lost. 

```
2015-08-05 01:07:34 INFO  Broker:27 - [Broker] initializing broker...
2015-08-05 01:07:34 INFO  Server:67 - Using config file: D:\workspace\Testbed_2.0\config\moquette.conf
2015-08-05 01:07:34 INFO  Server:91 - Persistent store file: ./resource/moquette_store.mapdb
2015-08-05 01:07:34 INFO  FileAuthenticator:43 - Loading password file: config\password_file.conf
2015-08-05 01:07:34 INFO  NettyAcceptor:132 - Server binded host: 0.0.0.0, port: 18830
2015-08-05 01:07:34 INFO  NettyAcceptor:132 - Server binded host: 0.0.0.0, port: 28080
2015-08-05 01:07:34 INFO  NettyAcceptor:196 - SSL is disabled
2015-08-05 01:07:34 INFO  Broker:35 - Server started, version 0.7-SNAPSHOT
2015-08-05 01:07:34 WARN  SmartObjectManager:161 - WARNING: ContextManager is not assigned.
2015-08-05 01:07:34 INFO  PubSubManager:68 - [PubSubMgr] global broker address = tcp://192.168.0.22:18830
2015-08-05 01:07:34 INFO  MQTTClient:125 -  - A new MQTTClient with client ID 'TestF-PlacenessMiner' has started. (subscriber class = PlacenessMiner)
2015-08-05 01:07:34 WARN  PubSubManager:88 - [PubSubMgr][joinGlobalPubSubNet] funcToMethMap is null in TestF-PlacenessMiner, nothing is subscribed for calling methods.
2015-08-05 01:07:34 INFO  NettyMQTTHandler:45 - Received a message of type CONNECT
2015-08-05 01:07:34 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping CONNECT
2015-08-05 01:07:34 INFO  ProtocolProcessor:235 - Create persistent session for clientID <TestF-PlacenessMiner>
2015-08-05 01:07:35 INFO  ProtocolProcessor:237 - Connected client ID <TestF-PlacenessMiner> with clean session false
2015-08-05 01:07:35 INFO  ProtocolProcessor:257 - No stored messages for client <TestF-PlacenessMiner>
2015-08-05 01:07:35 INFO  NettyMQTTHandler:45 - Received a message of type SUBSCRIBE
2015-08-05 01:07:35 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping SUBSCRIBE
2015-08-05 01:07:35 INFO  ProtocolProcessor:617 - <TestF-PlacenessMiner> subscribed to topic <Command/Context/Place/N1SeminarRoom825/Service/#> with QoS 2 - EXACTLY_ONCE
2015-08-05 01:07:35 INFO  PubSubManager:68 - [PubSubMgr] global broker address = tcp://192.168.0.22:18830
2015-08-05 01:07:35 INFO  MQTTClient:125 -  - A new MQTTClient with client ID 'TestF' has started. (subscriber class = AgentSimulatorService)
2015-08-05 01:07:35 WARN  PubSubManager:88 - [PubSubMgr][joinGlobalPubSubNet] funcToMethMap is null in TestF, nothing is subscribed for calling methods.
2015-08-05 01:07:35 WARN  PubSubManager:144 - [PubSubMgr][joinGlobalPubSubNet] funcToMethMap is null in TestF, nothing is subscribed for calling methods.
2015-08-05 01:07:35 INFO  NettyMQTTHandler:45 - Received a message of type CONNECT
2015-08-05 01:07:35 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping CONNECT
2015-08-05 01:07:35 INFO  ProtocolProcessor:235 - Create persistent session for clientID <TestF>
2015-08-05 01:07:35 INFO  NettyMQTTHandler:45 - Received a message of type SUBSCRIBE
2015-08-05 01:07:35 INFO  ProtocolProcessor:237 - Connected client ID <TestF> with clean session false
2015-08-05 01:07:35 INFO  ProtocolProcessor:257 - No stored messages for client <TestF>
2015-08-05 01:07:35 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping SUBSCRIBE
2015-08-05 01:07:35 INFO  ProtocolProcessor:617 - <TestF> subscribed to topic <Command/+/Place/N1SeminarRoom825/Service/TestF/#> with QoS 2 - EXACTLY_ONCE
2015-08-05 01:07:39 INFO  PublishDecoder:38 - decode invoked with buffer UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 75, cap: 512)
2015-08-05 01:07:39 INFO  NettyMQTTHandler:45 - Received a message of type PUBLISH
2015-08-05 01:07:39 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping PUBLISH
2015-08-05 01:07:39 INFO  ProtocolProcessor:299 - PUBLISH from clientID <TestF-PlacenessMiner> on topic <Command/Context/Place/N1SeminarRoom825/Service/TestA/C/D> with QoS EXACTLY_ONCE
2015-08-05 01:07:39 INFO  NettyMQTTHandler:45 - Received a message of type PUBREL
2015-08-05 01:07:39 INFO  SimpleMessaging:151 - onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping PUBREL
2015-08-05 01:07:39 INFO  ProtocolProcessor:407 - send publish message to <TestA> on topic <Command/Context/Place/N1SeminarRoom825/Service/TestA/C/D>
2015-08-05 01:07:39 ERROR SimpleMessaging:173 - Serious error processing the message org.eclipse.moquette.proto.messages.PubRelMessage@2a310caf for session [clientID: TestF-PlacenessMiner]org.eclipse.moquette.server.netty.NettyChannel@7a37cacc
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:167)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <TestA> in cache <{TestF-PlacenessMiner=ConnectionDescriptor{m_clientID=TestF-PlacenessMiner, m_cleanSession=false}, TestF=ConnectionDescriptor{m_clientID=TestF, m_cleanSession=false}}>
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:425)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.forward2Subscribers(ProtocolProcessor.java:392)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPubRel(ProtocolProcessor.java:480)
    ... 11 more
```

**Comment by esistgut** [comment]
Same problem here:

```
Starting broker in embedded mode
starting proprs $props
0    [JavaFX Application Thread] INFO  Server  - Persistent store file: /home/esistgut/coding/idea/kartbroker/moquette_store.mapdb
518  [JavaFX Application Thread] INFO  NettyAcceptor  - Server binded host: 0.0.0.0, port: 1883
519  [JavaFX Application Thread] INFO  NettyAcceptor  - Server binded host: 0.0.0.0, port: 8080
23311 [pool-2-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <18-FE-34-9E-38-7F>
23415 [pool-2-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <18-FE-34-9E-38-7F>
23535 [pool-2-thread-1] INFO  ProtocolProcessor  - Connected client ID <18-FE-34-9E-38-7F> with clean session true
44906 [pool-2-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <18-FE-34-9E-38-7F> on topic <kart> with QoS EXACTLY_ONCE
52310 [pool-2-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <MainClient>
52427 [pool-2-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <MainClient>
52526 [pool-2-thread-1] INFO  ProtocolProcessor  - Connected client ID <MainClient> with clean session true
52527 [pool-2-thread-1] INFO  ProtocolProcessor  - <MainClient> subscribed to topic <kart> with QoS 1 - LEAST_ONE
60601 [pool-2-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <18-FE-34-9E-38-7F> on topic <kart> with QoS EXACTLY_ONCE
60608 [pool-2-thread-1] INFO  ProtocolProcessor  - send publish message to <MainClient> on topic <kart>
66291 [pool-2-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <18-FE-34-9E-38-7F> on topic <kart> with QoS EXACTLY_ONCE
66297 [pool-2-thread-1] INFO  ProtocolProcessor  - send publish message to <MainClient> on topic <kart>
81207 [pool-2-thread-1] INFO  ProtocolProcessor  - Found an existing connection with same client ID <18-FE-34-9E-38-7F>, forcing to close
81207 [pool-2-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <18-FE-34-9E-38-7F>
81417 [pool-2-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <18-FE-34-9E-38-7F>
81526 [pool-2-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <18-FE-34-9E-38-7F>
81650 [pool-2-thread-1] INFO  ProtocolProcessor  - Connected client ID <18-FE-34-9E-38-7F> with clean session true
81759 [pool-2-thread-1] INFO  ProtocolProcessor  - Lost connection with client <18-FE-34-9E-38-7F>
98911 [pool-2-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <18-FE-34-9E-38-7F> on topic <kart> with QoS EXACTLY_ONCE
98912 [pool-2-thread-1] ERROR SimpleMessaging  - Serious error processing the message org.eclipse.moquette.proto.messages.PublishMessage@e487b1 for session [clientID: 18-FE-34-9E-38-7F]org.eclipse.moquette.server.netty.NettyChannel@539afd5e
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.NullPointerException
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPubRec(ProtocolProcessor.java:459)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:330)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
    ... 11 more
```

Steps to reproduce:
1. start server
2. start client and connect
3. publish message
4. kill client
5. restart and reconnect the client
6. try to publish again
7. error

**Comment by LiangCan** [comment]
esistgut

**Comment by LiangCan** [comment]
esistgut
    I have encountered this problem like you , you do not know how to solve it?

**Comment by esistgut** [comment]
No, I'm sorry, I can't help you, I moved away from Moquette and MQTT.
