### ISSUE TITLE
building from source causes error

### ISSUE THREAD

**Issue by arifainchtein** [moquette-io/moquette#402]
I was trying to build the project fro source, following the instructions, i cloned the repo, cd into it, typed : 

./gradlew clean distribution:distMoquetteZip

and got 

FAILURE: Build failed with an exception.

* What went wrong:
Project 'distribution' not found in root project 'moquette-parent'.

How can i build from source? I need to end up with a jar that contains the broker.
 I need the latest version since 0.10 has the bug that the file database keeps growing.

thanks

**Comment by RobLeighton** [comment]
change distribution in the command to moquette-distribution 

worked for me

**Comment by andsel** [comment]
I know,
yesterday creating (a partial release of 0.11 version) I've broke the
script because forced to load bintray credentials from my private
gradle.properties, I'll fix in the next days.
Thanks
  Andrea

**Comment by RobLeighton** [comment]
Hi Andrea,

While I have your attention – a quick question : should I be able to bind Moquette to the IP address of my network adapter for local network testing?
I get the following ...

7/05/2018 11:06:07,812 [main] INFO  NettyAcceptor initFactory 196  - Server bound to host=10.29.114.10, port=1883, protocol=TCP MQTT
Exception in thread "main" java.net.BindException: Cannot assign requested address: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)

Rob Leighton

Developer
M2M Intelligence.

**Comment by andsel** [comment]
In your moquette.conf file you have host <IP> by default it binds to all
interfaces (0.0.0.0)
Look at
https://github.com/andsel/moquette/blob/master/broker/config/moquette.conf

I've to improve the documentation at moquette.io

 Andrea

**Comment by RobLeighton** [comment]
Thanks Andrea, 

I saw that and changed it because I don’t seem to be able to publish to moquette from another device on my LAN – I’ll investigate other outside influences (firewalls etc)

Rob Leighton

Developer
M2M Intelligence.

**Comment by RobLeighton** [comment]
Hi Andrea,

Operator error – wrong IP Address for local device ... fixed!

Rob Leighton

Developer
M2M Intelligence.

**Comment by andsel** [comment]
Version 0.11 has been deployed to bintray
or you can build and deploy on your local m2  repo with "./gradlew
publishToMavenLocal"

 Andrea

**Comment by arifainchtein** [comment]
hey, thanks for that .. :)

**Comment by davidgraeff** [comment]
@andsel Can you deploy to github as well? :)

**Comment by andsel** [comment]
@davidgraeff it's already on github

**Comment by davidgraeff** [comment]
I mean the releases page: https://github.com/andsel/moquette/releases
That's where I get notifications of new releases. I just discovered that you released by accident ^^.

**Comment by andsel** [comment]
Thanks @davidgraeff I've done it:-) sorry  for the incovenient
