### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.moquette.spi.impl.subscriptions.Subscription in Android

### ISSUE THREAD

**Issue by mstranne** [moquette-io/moquette#484]
### Expected behavior
I used moquette broker already on android within an Unity application and it worked fine.

Now I have to write a native android app acting as an mqtt broke.

### Actual behavior
It crashes with an ClassNotFoundException on startServer

### Steps to reproduce
I am using following dependencies:

`    compile 'io.moquette:moquette-netty-parser:0.8.1'
    compile 'io.moquette:moquette-broker:0.8.1'
    compile 'io.moquette:moquette-parser-commons:0.8.1'
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'`

OnCreate I start the server as following after checking all permissions:

`server = new Server();

            MemoryConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath()+ File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_MAP_DB_FILENAME);
           
            try {
                server.startServer(memoryConfig);
                //server.startServer();
            } catch (IOException e) {
                e.printStackTrace();
            }`

**Comment by andsel** [comment]
Hi @mstranne which version of moquette are you using? since version 0.10 moquette in in the namespace io.moquette and not org.eclipse.moquette. Only the latest version of moquette is supported.

**Comment by mstranne** [comment]
As you can see above, I am using version 0.8.1, so then the Error is even more confusing

**Comment by mstranne** [comment]
Ok I changed the broker version to 0.12.1

Then I also had to change 

`        memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath()+ File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_MAP_DB_FILENAME);`

to

`memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath()+ File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_H2_DB_FILENAME);`

and now I get following error on startServer:

 Caused by: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43)
        at io.moquette.broker.Server.startServer(Server.java:166)
        at io.moquette.broker.Server.startServer(Server.java:133)
        at io.moquette.broker.Server.startServer(Server.java:120)
        at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43) 
        at io.moquette.broker.Server.startServer(Server.java:166) 
        at io.moquette.broker.Server.startServer(Server.java:133) 
        at io.moquette.broker.Server.startServer(Server.java:120) 
        at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by andsel** [comment]
I don't have too much experience with Android, giving a look at stacktrace
seems like that Android didn't find something, but probably the stack trace
is more wide than you posted

 Andrea

**Comment by mstranne** [comment]
uh sorry, didnt got everything.

here is all:

`06-21 12:03:15.849 7443-7490/testtest4.tu.com.mqttandroid I/com.mqttandroi: ProcessProfilingInfo new_methods=743 is saved saved_to_disk=1 resolve_classes_delay=8000
06-21 12:03:19.290 7443-7443/testtest4.tu.com.mqttandroid W/System.err: log4j:WARN No appenders could be found for logger (io.moquette.broker.Server).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
06-21 12:03:19.310 7443-7443/testtest4.tu.com.mqttandroid D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
06-21 12:03:19.311 7443-7443/testtest4.tu.com.mqttandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: testtest4.tu.com.mqttandroid, PID: 7443
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43)
        at io.moquette.broker.Server.startServer(Server.java:166)
        at io.moquette.broker.Server.startServer(Server.java:133)
        at io.moquette.broker.Server.startServer(Server.java:120)
        at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43) 
        at io.moquette.broker.Server.startServer(Server.java:166) 
        at io.moquette.broker.Server.startServer(Server.java:133) 
        at io.moquette.broker.Server.startServer(Server.java:120) 
        at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) `



and when I change my code from `server.startServer(memoryConfig);` to `server.startServer();` i get following error:


`06-24 10:31:00.131 28252-28252/testtest4.tu.com.mqttandroid W/com.mqttandroid: type=1400 audit(0.0:39705): avc: denied { search } for name="/" dev="configfs" ino=15673 scontext=u:r:untrusted_app:s0:c12,c257,c512,c768 tcontext=u:object_r:configfs:s0 tclass=dir permissive=0
06-24 10:31:00.144 28252-28252/testtest4.tu.com.mqttandroid D/AndroidRuntime: Shutting down VM
06-24 10:31:00.145 28252-28252/testtest4.tu.com.mqttandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: testtest4.tu.com.mqttandroid, PID: 28252
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.IllegalArgumentException: Can't locate file "null"
        at io.moquette.broker.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:60)
        at io.moquette.broker.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:36)
        at io.moquette.broker.Server.startServer(Server.java:72)
        at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:58)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
06-24 10:31:00.162 28252-28252/testtest4.tu.com.mqttandroid I/Process: Sending signal. PID: 28252 SIG: 9`

**Comment by beniroquai** [comment]
Hey, did you ever solve the problem? It seems I'm having the same issue here..

**Comment by necoicould** [comment]
@andsel 
@mstranne 
is there any solution yet`?

**Comment by necoicould** [comment]
> 
> 
> uh sorry, didnt got everything.
> 
> here is all:
> 
> `06-21 12:03:15.849 7443-7490/testtest4.tu.com.mqttandroid I/com.mqttandroi: ProcessProfilingInfo new_methods=743 is saved saved_to_disk=1 resolve_classes_delay=8000
> 06-21 12:03:19.290 7443-7443/testtest4.tu.com.mqttandroid W/System.err: log4j:WARN No appenders could be found for logger (io.moquette.broker.Server).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> 06-21 12:03:19.310 7443-7443/testtest4.tu.com.mqttandroid D/AndroidRuntime: Shutting down VM
> 
> ```
> --------- beginning of crash
> ```
> 
> 06-21 12:03:19.311 7443-7443/testtest4.tu.com.mqttandroid E/AndroidRuntime: FATAL EXCEPTION: main
> Process: testtest4.tu.com.mqttandroid, PID: 7443
> java.lang.IllegalStateException: Could not execute method for android:onClick
> at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
> at android.view.View.performClick(View.java:6608)
> at android.view.View.performClickInternal(View.java:6585)
> at android.view.View.access$3100(View.java:785)
> at android.view.View$PerformClick.run(View.java:25921)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:201)
> at android.app.ActivityThread.main(ActivityThread.java:6815)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
> at android.view.View.performClick(View.java:6608) 
> at android.view.View.performClickInternal(View.java:6585) 
> at android.view.View.access$3100(View.java:785) 
> at android.view.View$PerformClick.run(View.java:25921) 
> at android.os.Handler.handleCallback(Handler.java:873) 
> at android.os.Handler.dispatchMessage(Handler.java:99) 
> at android.os.Looper.loop(Looper.java:201) 
> at android.app.ActivityThread.main(ActivityThread.java:6815) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
> Caused by: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
> at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43)
> at io.moquette.broker.Server.startServer(Server.java:166)
> at io.moquette.broker.Server.startServer(Server.java:133)
> at io.moquette.broker.Server.startServer(Server.java:120)
> at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56)
> at java.lang.reflect.Method.invoke(Native Method) 
> at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
> at android.view.View.performClick(View.java:6608) 
> at android.view.View.performClickInternal(View.java:6585) 
> at android.view.View.access$3100(View.java:785) 
> at android.view.View$PerformClick.run(View.java:25921) 
> at android.os.Handler.handleCallback(Handler.java:873) 
> at android.os.Handler.dispatchMessage(Handler.java:99) 
> at android.os.Looper.loop(Looper.java:201) 
> at android.app.ActivityThread.main(ActivityThread.java:6815) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
> Caused by: java.lang.ClassCastException: Bootstrap method returned null
> at io.moquette.persistence.H2Builder.initStore(H2Builder.java:43) 
> at io.moquette.broker.Server.startServer(Server.java:166) 
> at io.moquette.broker.Server.startServer(Server.java:133) 
> at io.moquette.broker.Server.startServer(Server.java:120) 
> at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:56) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
> at android.view.View.performClick(View.java:6608) 
> at android.view.View.performClickInternal(View.java:6585) 
> at android.view.View.access$3100(View.java:785) 
> at android.view.View$PerformClick.run(View.java:25921) 
> at android.os.Handler.handleCallback(Handler.java:873) 
> at android.os.Handler.dispatchMessage(Handler.java:99) 
> at android.os.Looper.loop(Looper.java:201) 
> at android.app.ActivityThread.main(ActivityThread.java:6815) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) `
> 
> and when I change my code from `server.startServer(memoryConfig);` to `server.startServer();` i get following error:
> 
> `06-24 10:31:00.131 28252-28252/testtest4.tu.com.mqttandroid W/com.mqttandroid: type=1400 audit(0.0:39705): avc: denied { search } for name="/" dev="configfs" ino=15673 scontext=u:r:untrusted_app:s0:c12,c257,c512,c768 tcontext=u:object_r:configfs:s0 tclass=dir permissive=0 06-24 10:31:00.144 28252-28252/testtest4.tu.com.mqttandroid D/AndroidRuntime: Shutting down VM 06-24 10:31:00.145 28252-28252/testtest4.tu.com.mqttandroid E/AndroidRuntime: FATAL EXCEPTION: main Process: testtest4.tu.com.mqttandroid, PID: 28252 java.lang.IllegalStateException: Could not execute method for android:onClick at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390) at android.view.View.performClick(View.java:6608) at android.view.View.performClickInternal(View.java:6585) at android.view.View.access$3100(View.java:785) at android.view.View$PerformClick.run(View.java:25921) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java:6815) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method) at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) at android.view.View.performClick(View.java:6608)  at android.view.View.performClickInternal(View.java:6585)  at android.view.View.access$3100(View.java:785)  at android.view.View$PerformClick.run(View.java:25921)  at android.os.Handler.handleCallback(Handler.java:873)  at android.os.Handler.dispatchMessage(Handler.java:99)  at android.os.Looper.loop(Looper.java:201)  at android.app.ActivityThread.main(ActivityThread.java:6815)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)  Caused by: java.lang.IllegalArgumentException: Can't locate file "null" at io.moquette.broker.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:60) at io.moquette.broker.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:36) at io.moquette.broker.Server.startServer(Server.java:72) at testtest4.tu.com.mqttandroid.MainActivity.OnClickStartServer(MainActivity.java:58) at java.lang.reflect.Method.invoke(Native Method)  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)  at android.view.View.performClick(View.java:6608)  at android.view.View.performClickInternal(View.java:6585)  at android.view.View.access$3100(View.java:785)  at android.view.View$PerformClick.run(View.java:25921)  at android.os.Handler.handleCallback(Handler.java:873)  at android.os.Handler.dispatchMessage(Handler.java:99)  at android.os.Looper.loop(Looper.java:201)  at android.app.ActivityThread.main(ActivityThread.java:6815)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)  06-24 10:31:00.162 28252-28252/testtest4.tu.com.mqttandroid I/Process: Sending signal. PID: 28252 SIG: 9`

could you solve it ?

**Comment by mstranne** [comment]
I switched to mosquitto, building it as a c library, which can be used crossplattform

**Comment by necoicould** [comment]
> 
> 
> I switched to mosquitto, building it as a c library, which can be used crossplattform

do you have any tutorial for that? my aim is to run mqtt broker (moquette) inside an android app

**Comment by andsel** [comment]
Hi @necoicould  thank's for reporting it, in order to investigate it:
- could you describe better how to create a reproducer?
- could you reproduce it outside of Android environment?
- which Moquette version are you using?
