### ISSUE TITLE
Connection Lost on Subscribe Message

### ISSUE THREAD

**Issue by hasanalpzengin** [moquette-io/moquette#500]
I used moquette on Android to create broker but when I send subscribe message from client it drops client's connection immediately.
Publish and connection messages can be received without any problem. But my problem is on subscribing.
Here is my config. I'm handling broker with service.
`private Properties defaultConfig() {
        Properties props = new Properties();
        props.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, this.getExternalFilesDir(null).getAbsolutePath() + File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_H2_DB_FILENAME);
        props.setProperty(BrokerConstants.PORT_PROPERTY_NAME, "1883");
        props.setProperty(BrokerConstants.NEED_CLIENT_AUTH, "false");
        props.setProperty(BrokerConstants.HOST_PROPERTY_NAME, serverIP);
        //props.setProperty(BrokerConstants.WEB_SOCKET_PORT_PROPERTY_NAME, String.valueOf(BrokerConstants.WEBSOCKET_PORT));
        props.setProperty(BrokerConstants.NETTY_SO_KEEPALIVE_PROPERTY_NAME, "true");
        props.setProperty(BrokerConstants.NETTY_TCP_NODELAY_PROPERTY_NAME, "true");
        props.setProperty(BrokerConstants.NETTY_SO_REUSEADDR_PROPERTY_NAME, "true");
        props.setProperty(BrokerConstants.NETTY_CHANNEL_TIMEOUT_SECONDS_PROPERTY_NAME, "100");
        props.setProperty(BrokerConstants.NETTY_SO_BACKLOG_PROPERTY_NAME, "128");
        props.setProperty(BrokerConstants.BROKER_INTERCEPTOR_THREAD_POOL_SIZE, String.valueOf(Integer.MAX_VALUE));
        props.setProperty(BrokerConstants.ALLOW_ANONYMOUS_PROPERTY_NAME, "true");
        props.setProperty(BrokerConstants.ALLOW_ZERO_BYTE_CLIENT_ID_PROPERTY_NAME, "true");
        props.setProperty(BrokerConstants.REAUTHORIZE_SUBSCRIPTIONS_ON_CONNECT, "true");
        return props;
    }`

This is error message from Paho's MQTT Client:
`E/MQTT Thread: Client Connection Lost Error: 
    Connection lost (32109) - java.net.SocketException: Connection reset
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:192)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at java.net.SocketInputStream.read(SocketInputStream.java:206)
        at java.io.DataInputStream.readByte(DataInputStream.java:268)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)`

QoS = 0

Do you have any clue for my problem ?

**Comment by hasanalpzengin** [comment]
Version 0.12.1 have that I can subscribe in 0.11 without any problem.
