### ISSUE TITLE
Android: java.lang.NoSuchMethodError: No static method join

### ISSUE THREAD

**Issue by hasanalpzengin** [moquette-io/moquette#501]
### Expected behavior
On subscribe it gives no static method error.
### Actual behavior
```java
I/System.out: 182 [nioEventLoopGroup-3-1] ERROR io.moquette.broker.NewNettyMQTTHandler  - Error processing protocol message: SUBSCRIBE
    java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at io.moquette.broker.subscriptions.Topic.<init>(Topic.java:59)
        at io.moquette.broker.subscriptions.Topic.exceptHeadToken(Topic.java:151)
        at io.moquette.broker.subscriptions.CTrie.createPathRec(CTrie.java:133)
        at io.moquette.broker.subscriptions.CTrie.createNodeAndInsertSubscription(CTrie.java:124)
        at io.moquette.broker.subscriptions.CTrie.insert(CTrie.java:108)
        at io.moquette.broker.subscriptions.CTrie.addToTree(CTrie.java:94)
        at io.moquette.broker.subscriptions.CTrieSubscriptionDirectory.add(CTrieSubscriptionDirectory.java:87)
        at io.moquette.broker.PostOffice.subscribeClientToTopics(PostOffice.java:81)
        at io.moquette.broker.MQTTConnection.processSubscribe(MQTTConnection.java:306)
        at io.moquette.broker.MQTTConnection.handleMessage(MQTTConnection.java:70)
        at io.moquette.broker.NewNettyMQTTHandler.channelRead(NewNettyMQTTHandler.java:58)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.moquette.broker.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:46)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.moquette.broker.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.moquette.broker.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:51)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
I/System.out:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:761)
    184 [nioEventLoopGroup-3-1] INFO io.moquette.broker.NewNettyMQTTHandler  - Closed client channel due to exception in processing
    184 [nioEventLoopGroup-3-1] INFO io.moquette.broker.metrics.MQTTMessageLogger  - Channel closed <vvvv>
    184 [nioEventLoopGroup-3-1] INFO io.moquette.broker.MQTTConnection  - Notifying connection lost event. CId: vvvv, channel: [id: 0xf3b05337, L:/192.168.1.180:1883 ! R:/192.168.1.180:36750]
```
### Steps to reproduce
implement:
implementation 'io.moquette:moquette-broker:0.12.1'
implementation 'io.moquette:moquette-netty-parser:0.8.1'
topic: /vv/join
qos: 0
action: send subscribe message
java version: 1.8
### Moquette MQTT version
0.12.1
### JVM version (e.g. `java -version`)
0.8.1
### OS version (e.g. `uname -a`)
Android 7.1

**Comment by PCBzan** [comment]
hi 

i need a broker for android

have you ever work on android broker such as moquette for android or something like that ?

**Comment by hasanalpzengin** [comment]
I'm using moquette broker on my project. That problem only occurs on Android 7.1 and under. after android 8.0 application starts with java 8 but on android 7.1 application starts with java 6. I don't know the reason but I discovered that. If you use android 8.0 and above there is no problem.

**Comment by andsel** [comment]
Hi but Moquette broker doesn't support Android platform
