### ISSUE TITLE
IOException: Address already in use

### ISSUE THREAD

**Issue by rasik1991** [moquette-io/moquette#511]
### Expected behavior
MQTT Broker should be start

### Actual behavior
IOException: Address already in use

### Steps to reproduce
try {
            io.moquette.server.Server server = new io.moquette.server.Server();
            MemoryConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_MAP_DB_FILENAME);
            server.startServer(memoryConfig);
            LogUtils.e(TAG, " Broker Server Started Successfully!!! ");
        } catch (IOException e) {
            e.printStackTrace();
            LogUtils.e(TAG, " Broker Server Not Connected IOException: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            LogUtils.e(TAG, " Broker Server Not Connected Exception: " + e.getMessage());
        }

### Minimal yet complete reproducer code (or URL to code) or complete log file

2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err: java.net.BindException: Address already in use
2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err:     at sun.nio.ch.Net.bind0(Native Method)
2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err:     at sun.nio.ch.Net.bind(Net.java:442)
2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err:     at sun.nio.ch.Net.bind(Net.java:434)
2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err:     at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224)
2020-01-01 16:08:01.513 3821-3821/com.pyrotech W/System.err:     at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:440)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:425)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
2020-01-01 16:08:01.514 3821-3821/com.pyrotech W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
2020-01-01 16:08:01.515 3821-3821/com.pyrotech W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
2020-01-01 16:08:01.515 3821-3821/com.pyrotech W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2020-01-01 16:08:01.515 3821-3821/com.pyrotech W/System.err:     at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2020-01-01 16:08:01.515 3821-3821/com.pyrotech W/System.err:     at java.lang.Thread.run(Thread.java:764)

### Moquette MQTT version

//MQTT Client
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

    //MQTT Broker
    implementation 'io.moquette:moquette-netty-parser:0.8.1'
    implementation 'io.moquette:moquette-broker:0.8.1'
    implementation 'io.moquette:moquette-parser-commons:0.8.1'

### JVM version (e.g. `java -version`)
JAVA :  VERSION_1_8

### OS version (e.g. `uname -a`)
Android9(Pie)

**Comment by rasik1991** [comment]
My Bug fixed when i changed  library version like bellow:

`//MQTT Client
  implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
  implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
  implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

  //MQTT Broker
  implementation 'io.moquette:moquette-netty-parser:0.9'
  implementation 'io.moquette:moquette-broker:0.12.1'
  implementation 'io.moquette:moquette-parser-commons:0.8.1'

//Broker connection , add in onCreate
private void startBrokerServer() {
        try {
            brokerServer = new Server();
            IConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_H2_DB_FILENAME);
            brokerServer.startServer(memoryConfig);
            startMQTTClient();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

private void startMQTTClient() {

       String clientId = MqttClient.generateClientId();
	 String  serverUri = "tcp://" + IP + ":1883";
     MqttAndroidClient   mqttAndroidClient = new MqttAndroidClient(activity, serverUri, clientId);
        mqttAndroidClient.setCallback(new MqttCallbackExtended() {
            @Override
            public void connectComplete(boolean reconnect, String serverURI) {

                if (reconnect) {
                    LogUtils.e(TAG, " Reconnected to : " + serverURI);
                    // Because Clean Session is true, we need to re-subscribe
                    subscribeToTopic();
                    showToast("Client Reconnected");
                } else {
                    LogUtils.e(TAG, " mqttAndroidClient Connected to: " + serverURI);
                    showToast("Client  Reconnected to: " + serverURI);
                }
            }

            @Override
            public void connectionLost(Throwable cause) {
                LogUtils.e(TAG, " The Connection was lost.");
                showToast("Client connection lost");
            }

            @Override
            public void messageArrived(String topic, MqttMessage message) throws Exception {
                LogUtils.e(TAG, " messageArrived topic: " + topic);
                String strMsg = new String(message.getPayload());
                LogUtils.e(TAG, " messageArrived message: " + strMsg);
                int value = Integer.valueOf(strMsg);
                LogUtils.e(TAG, " messageArrived message Integer: " + value);
            }

            @Override
            public void deliveryComplete(IMqttDeliveryToken token) {
                LogUtils.e(TAG, " deliveryComplete  token: " + token);
            }
        });

        MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
        mqttConnectOptions.setAutomaticReconnect(true);
        mqttConnectOptions.setCleanSession(false);

        try {
            //addToHistory("Connecting to " + serverUri);
            mqttAndroidClient.connect(mqttConnectOptions, null, new IMqttActionListener() {
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
                    disconnectedBufferOptions.setBufferEnabled(true);
                    disconnectedBufferOptions.setBufferSize(100);
                    disconnectedBufferOptions.setPersistBuffer(false);
                    disconnectedBufferOptions.setDeleteOldestMessages(false);
                    mqttAndroidClient.setBufferOpts(disconnectedBufferOptions);
                    subscribeToTopic();
                    LogUtils.e(TAG, " mqttAndroidClient connection Success: ");
                    showToast("Client connection success");
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable e) {
//                    addToHistory("Failed to connect to: " + serverUri);
                    LogUtils.e(TAG, " mqttAndroidClient connection failed Exception: " + e.getMessage());
                    showToast("Client connection failed");
                }
            });
        } catch (MqttException ex) {
            ex.printStackTrace();
        }
    }

@Override
    protected void onDestroy() {
        try {
            mqttAndroidClient.unregisterResources();
            mqttAndroidClient.close();
            LogUtils.e(TAG, " mqttAndroidClient Closed ");
        } catch (Exception e) {
            e.printStackTrace();
            LogUtils.e(TAG, " mqttAndroidClient close error: " + e.getMessage());
        }
        try {
            brokerServer.stopServer();
            LogUtils.e(TAG, " brokerServer Closed ");
        } catch (Exception e) {
            e.printStackTrace();
            LogUtils.e(TAG, " brokerServer close error: " + e.getMessage());
        }
        super.onDestroy();
    }
`


**Note:** is still not working then uninstall apk and reboot android device and then install again
