### ISSUE TITLE
Could not instantiate class

### ISSUE THREAD

**Issue by rasik1991** [moquette-io/moquette#512]
### Expected behavior
should be MQTT Broker Server connection  

### Actual behavior
MQTT Broker Server connection failed

### Steps to reproduce

try {
            io.moquette.server.Server server = new io.moquette.server.Server();
            MemoryConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_MAP_DB_FILENAME);
            server.startServer(memoryConfig);

        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

### Minimal yet complete reproducer code (or URL to code) or complete log file

2020-01-03 17:52:47.308 15827-15827/com.rasikapp E/MainActivity:  Broker Server port 1883
2020-01-03 17:52:47.361 15827-15827/com.rasikapp W/System.err: log4j:WARN No appenders could be found for logger (io.moquette.server.Server).
2020-01-03 17:52:47.362 15827-15827/com.rasikapp W/System.err: log4j:WARN Please initialize the log4j system properly.
2020-01-03 17:52:47.362 15827-15827/com.rasikapp W/System.err: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2020-01-03 17:52:48.613 15827-15827/com.rasikapp W/com.rasikapp: Accessing hidden method Ljava/io/ObjectStreamClass;->getConstructorId(Ljava/lang/Class;)J (light greylist, reflection)
2020-01-03 17:52:48.663 15827-15827/com.rasikapp W/System.err: java.lang.RuntimeException: Could not instantiate class
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:135)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:121)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.Store.deserialize(Store.java:297)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
2020-01-03 17:52:48.664 15827-15827/com.rasikapp W/System.err:     at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.StoreWAL.get(StoreWAL.java:320)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.Caches$HashTable.get(Caches.java:246)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$HashIterator.findNextLinkedNodeRecur(HTreeMap.java:1089)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$HashIterator.findNextLinkedNode(HTreeMap.java:1054)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$HashIterator.<init>(HTreeMap.java:978)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$KeyIterator.<init>(HTreeMap.java:1116)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at org.mapdb.HTreeMap$KeySet.iterator(HTreeMap.java:818)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at io.moquette.spi.persistence.MapDBSessionsStore.listAllSubscriptions(MapDBSessionsStore.java:102)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at io.moquette.spi.impl.subscriptions.SubscriptionsStore.init(SubscriptionsStore.java:105)
2020-01-03 17:52:48.665 15827-15827/com.rasikapp W/System.err:     at io.moquette.spi.impl.SimpleMessaging.init(SimpleMessaging.java:102)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at io.moquette.server.Server.startServer(Server.java:125)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at io.moquette.server.Server.startServer(Server.java:110)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at io.moquette.server.Server.startServer(Server.java:102)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at com.rasikapp.MainActivity.startBrokerServer(MainActivity.java:112)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at com.rasikapp.MainActivity.init(MainActivity.java:80)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at com.rasikapp.MainActivity.checkStoragePermission(MainActivity.java:52)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at com.rasikapp.MainActivity.onCreate(MainActivity.java:45)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at android.app.Activity.performCreate(Activity.java:7327)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at android.app.Activity.performCreate(Activity.java:7318)
2020-01-03 17:52:48.666 15827-15827/com.rasikapp W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3105)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7100)
2020-01-03 17:52:48.667 15827-15827/com.rasikapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err: Caused by: java.lang.NoSuchMethodException: io.moquette.spi.persistence.MapDBPersistentStore$PersistentSession.<init> []
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err:     at java.lang.Class.getConstructor0(Class.java:2328)
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err:     at java.lang.Class.getConstructor(Class.java:1725)
2020-01-03 17:52:48.668 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerPojo.createInstanceSkippinkConstructor(SerializerPojo.java:579)
2020-01-03 17:52:48.669 15827-15827/com.rasikapp W/System.err:     at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:467)
2020-01-03 17:52:48.669 15827-15827/com.rasikapp W/System.err: 	... 41 more
2020-01-03 17:52:48.669 15827-15827/com.rasikapp E/MainActivity:  Broker Server Not Connected Exception: Could not instantiate class

### Moquette MQTT version
   //Broker
   implementation 'io.moquette:moquette-netty-parser:0.8.1'
    implementation 'io.moquette:moquette-broker:0.8.1'
    implementation 'io.moquette:moquette-parser-commons:0.8.1'

   //MQTT
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

### JVM version (e.g. `java -version`)
JAVA: VERSION_1_8

### OS version (e.g. `uname -a`)
Android9(Pie)

**Comment by rasik1991** [comment]
My Bug fixed when i changed  library version like bellow:

`//MQTT Client
  implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
  implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
  implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

  //MQTT Broker
  implementation 'io.moquette:moquette-netty-parser:0.9'
  implementation 'io.moquette:moquette-broker:0.12.1'
  implementation 'io.moquette:moquette-parser-commons:0.8.1'

//Broker connection , add in onCreate
private void startBrokerServer() {
        try {
            brokerServer = new Server();
            IConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_H2_DB_FILENAME);
            brokerServer.startServer(memoryConfig);
            startMQTTClient();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

private void startMQTTClient() {

       String clientId = MqttClient.generateClientId();
	 String  serverUri = "tcp://" + IP + ":1883";
     MqttAndroidClient   mqttAndroidClient = new MqttAndroidClient(activity, serverUri, clientId);
        mqttAndroidClient.setCallback(new MqttCallbackExtended() {
            @Override
            public void connectComplete(boolean reconnect, String serverURI) {

                if (reconnect) {
                    LogUtils.e(TAG, " Reconnected to : " + serverURI);
                    // Because Clean Session is true, we need to re-subscribe
                    subscribeToTopic();
                    showToast("Client Reconnected");
                } else {
                    LogUtils.e(TAG, " mqttAndroidClient Connected to: " + serverURI);
                    showToast("Client  Reconnected to: " + serverURI);
                }
            }

            @Override
            public void connectionLost(Throwable cause) {
                LogUtils.e(TAG, " The Connection was lost.");
                showToast("Client connection lost");
            }

            @Override
            public void messageArrived(String topic, MqttMessage message) throws Exception {
                LogUtils.e(TAG, " messageArrived topic: " + topic);
                String strMsg = new String(message.getPayload());
                LogUtils.e(TAG, " messageArrived message: " + strMsg);
                int value = Integer.valueOf(strMsg);
                LogUtils.e(TAG, " messageArrived message Integer: " + value);
            }

            @Override
            public void deliveryComplete(IMqttDeliveryToken token) {
                LogUtils.e(TAG, " deliveryComplete  token: " + token);
            }
        });

        MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
        mqttConnectOptions.setAutomaticReconnect(true);
        mqttConnectOptions.setCleanSession(false);

        try {
            //addToHistory("Connecting to " + serverUri);
            mqttAndroidClient.connect(mqttConnectOptions, null, new IMqttActionListener() {
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
                    disconnectedBufferOptions.setBufferEnabled(true);
                    disconnectedBufferOptions.setBufferSize(100);
                    disconnectedBufferOptions.setPersistBuffer(false);
                    disconnectedBufferOptions.setDeleteOldestMessages(false);
                    mqttAndroidClient.setBufferOpts(disconnectedBufferOptions);
                    subscribeToTopic();
                    LogUtils.e(TAG, " mqttAndroidClient connection Success: ");
                    showToast("Client connection success");
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable e) {
//                    addToHistory("Failed to connect to: " + serverUri);
                    LogUtils.e(TAG, " mqttAndroidClient connection failed Exception: " + e.getMessage());
                    showToast("Client connection failed");
                }
            });
        } catch (MqttException ex) {
            ex.printStackTrace();
        }
    }

@Override
    protected void onDestroy() {
        try {
            mqttAndroidClient.unregisterResources();
            mqttAndroidClient.close();
            LogUtils.e(TAG, " mqttAndroidClient Closed ");
        } catch (Exception e) {
            e.printStackTrace();
            LogUtils.e(TAG, " mqttAndroidClient close error: " + e.getMessage());
        }
        try {
            brokerServer.stopServer();
            LogUtils.e(TAG, " brokerServer Closed ");
        } catch (Exception e) {
            e.printStackTrace();
            LogUtils.e(TAG, " brokerServer close error: " + e.getMessage());
        }
        super.onDestroy();
    }
`


**Note:** is still not working then uninstall apk and reboot android device and then install again

**Comment by rasik1991** [comment]
issue fixed with above code
