### ISSUE TITLE
queue is full

### ISSUE THREAD

**Issue by arifainchtein** [moquette-io/moquette#521]
Hello,
I am using version 0.11 and I am getting this error.  Any suggestions as to why its happening and how do i prevent it from happening?
Thanks

`7013256 [nioEventLoopGroup-3-1] INFO  ProtocolProcessor  - Processing PUBLISH message. CId=ZhinuHeartPublisher, topic=OrganismStatus, messageId=9663, qos=AT_LEAST_ONCE
97013256 [nioEventLoopGroup-3-1] INFO  MessagesPublisher  - Sending publish message to subscribers. ClientId=ZhinuHeartPublisher, topic=OrganismStatus, messageId=9663
97013256 [nioEventLoopGroup-3-1] INFO  PersistentQueueMessageSender  - Sending PUBLISH message. MessageId=20314, CId=web_63, topic=OrganismStatus
97013256 [nioEventLoopGroup-3-1] INFO  ConnectionDescriptorStore  - Sending PUBLISH message CId=<web_63>, messageId=20314
97013256 [nioEventLoopGroup-3-1] ERROR NettyMQTTHandler  - Exception was caught while processing MQTT message, null
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
	at io.moquette.spi.DurableSession.enqueue(DurableSession.java:207)
	at io.moquette.spi.impl.MessagesPublisher.publish2Subscribers(MessagesPublisher.java:107)
	at io.moquette.spi.impl.MessagesPublisher.publish2Subscribers(MessagesPublisher.java:71)
	at io.moquette.spi.impl.Qos1PublishHandler.receivedPublishQos1(Qos1PublishHandler.java:70)
	at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:470)
	at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:49)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by gurk0001** [comment]
Any solution to this problem? I am facing exactly same issue

**Comment by gurk0001** [comment]
@andsel - could you please let us know what is the solution for this issue.? 
Is there a way to cleanup DurableSession for a given ClientId?

**Comment by andsel** [comment]
Hi @gurk0001  and @arifainchtein could set up a reproducer for this issue, without a reproducer or an an explanation of what you are doing it's little difficult to understand the problem from a stacktrace

**Comment by gurk0001** [comment]
@andsel 


It is reproducible.

MQTT BROKER VERSION 0.11

STEP 1: Create two clients say C1 and C2
STEP 2: Client(C1) has subscribed for the TOPIC- "T_1" with qos=1 and disconnect after 10 second
STEP 3: Client(C2) will publish messages to "T_1"
When you publish a message to broker having following information say every second for 1000 times:

**cleanSession=false, qos=1, retain=true, payload=“hello world”, topic="T_1"**

we get below exception on Broker side and any message sent by any client will not be able to publish message sucessfully.

------------

        2020-12-31 17:57:44.339  INFO 1 --- [ntLoopGroup-5-2] messageLogger                            : C->B PUBLISH <1234> to topics <T_1>

        2020-12-31 17:57:44.339  INFO 1 --- [ntLoopGroup-5-2] i.m.s.i.ProtocolProcessor                : Processing PUBLISH message. CId=1234, topic=T_1, messageId=89, qos=AT_LEAST_ONCE

        2020-12-31 17:57:44.339  INFO 1 --- [ntLoopGroup-5-2] i.m.s.i.MessagesPublisher                : Sending publish message to subscribers. ClientId=1234, topic=T_1, messageId=89

        2020-12-31 17:57:44.339  WARN 1 --- [ntLoopGroup-5-2] i.n.c.DefaultChannelPipeline             : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.`

         java.lang.IllegalStateException: Queue full

	at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[?:1.8.0_212]

	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[?:1.8.0_212]

	at io.moquette.spi.DurableSession.enqueue(DurableSession.java:191) ~[moquette-broker-0.11.jar:?]

	at io.moquette.spi.impl.MessagesPublisher.publish2Subscribers(MessagesPublisher.java:109) ~[moquette-broker-0.11.jar:?]

	at io.moquette.spi.impl.MessagesPublisher.publish2Subscribers(MessagesPublisher.java:72) ~[moquette-broker-0.11.jar:?]

	at io.moquette.spi.impl.Qos1PublishHandler.receivedPublishQos1(Qos1PublishHandler.java:74) ~[moquette-broker-0.11.jar:?]

	at io.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:460) ~[moquette-broker-0.11.jar:?]

	at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:58) [moquette-broker-0.11.jar:?]`


**I suspect the "max_queued" size of **sessionsStore** which is 1000 by default??**

I am using `serverObj.processor.sessionsStore.dropQueue("clientID")` to clear the queue alternatively. is there a better approach?

**Comment by andsel** [comment]
This problem is unrelated to `retain=true` it's related to the fact that messages is published with QoS1 and the subscriber session is with `cleanSession=false` so the broker has to keep all the messages that match any topic on which that client is subscribed. As I remember the MQTT specification doesn't say anything about this; I could imagine to expose a configuration setting to decide what to do in these cases.
- drop older messages queued on subscriber session.
- drop newer messages.

**Comment by gurk0001** [comment]
@andsel - that sounds excellent. we could have the control over it.

> drop older messages queued on subscriber session - **should solve these kind of issues.**

But, ideally, these case would arise if there is a subscription with `cleanSession=false` and `qos=1` 
and that client disappears !!

It would be nice to have a `configuraiton to unsubscribe all or certain topics on disconnect of a client after certain time duration (in days for example)`.

**Comment by andsel** [comment]
I'm planning to work on MQTT5 support, that version has similar concept, so I could eventually backport to MQTT3 handling

**Comment by arifainchtein** [comment]
Hello,
I am revisiting this topic because i am still getting the error.  I am still using 0.11 .  Are there any suggestions that i could do to mitigate this problem?

thanks

**Comment by arifainchtein** [comment]
i could migrate to 0.14 if that would help.  is there  a way to query Server as to the status of the queue?  Because if i could, i could check if its getting full, then i could stop and start the server as a way to flush the queue

**Comment by hylkevds** [comment]
Currently there is no way to inspect the session queues. Version 0.15 (and 0.14 I think) has no limit on the size of the queues.

If flushing the queue is an acceptable way to solve the issue, then apparently it is not a problem if messages are dropped. If this is the case, then why are you using `cleanSession=false`, `QoS 1` and a client that does not unsubscribe before disconnecting? You will run out of memory eventually if you do this, since Moquette currently has no limits on the Session.

The MQTT3.1.1 spec does state that the server is allowed to put limits on the Session lifetime (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180909).

**Comment by arifainchtein** [comment]
Hello,
Thanks for that.  Actually currently I am only connecting to the Server via the web using the Paho library.  Here is an example of how i subscribe to a topic:

`mqtt.subscribe(HEART_TOPIC_PULSE_STATUS_INFO, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:1});
	`
I am using QoS=1 but i dont really set the variable cleanSession anywhere. WIll try with QoS=0.
thanks

**Comment by hylkevds** [comment]
cleanSession is one of the connection options of the Paho MQTT Client: https://www.eclipse.org/paho/files/jsdoc/Paho.MQTT.Client.html

**Comment by arifainchtein** [comment]
Hello,
Thanks for your reply @hylkevds.  Here is the code that I use to connect the publishing client to the server:

`                        anMqttClient = new MqttClient(mqttBrokerAddress, mqttClientId, persistence);

			MqttConnectOptions connOpts = new MqttConnectOptions();

			connOpts.setAutomaticReconnect(true);

			connOpts.setCleanSession(true);

			connOpts.setKeepAliveInterval(300);

			logger.warn("Connecting to Heart: "+mqttBrokerAddress);

			anMqttClient.connect(connOpts);`

As you can see I am setting the CleanSession to true.  I am setting the QoS=1 when I publish messages.  The client never disconnects because it is an application that reads json data from text files and pushes them to the moquette server.

Here is the method that publishes the json messages to the moquette server:



`
public void publishToHeart(String topic, String messageText) {

		byte[] messageBytes = messageText.getBytes();

		MemoryPersistence persistence = new MemoryPersistence();

		MqttMessage message = new MqttMessage(messageBytes);
		message.setQos(1);
		message.setRetained(true);
		try {
			//logger.debug("about to Update the Heart, topic: " + topic  + " HEART_QUALITY_OF_SERVICE=" + TeleonomeConstants.HEART_QUALITY_OF_SERVICE + " message size=" +messageBytes.length + " anMqttClient.isConnected()=" + anMqttClient.isConnected());

			do {
				if(!anMqttClient.isConnected()) {
					logger.warn("Reconnecting to heart");
					anMqttClient.reconnect();
					try {
						Thread.sleep(10000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}	
			}while(!anMqttClient.isConnected());



			anMqttClient.publish(topic, message);
			//	logger.debug("published  to " + topic + "  in mqtt");

		} catch (MqttException e) {
			// TODO Auto-generated catch block
			logger.warn("Exception publishing to heart:" + Utils.getStringException(e));

		}
	}`

the `messageText` is a json file that can be big ie 1mb.    The publishing client is reading data from the local hard drive.  This data is actually uploaded from remote iot devices.  Each iot device sftp the json files once per minute.  So if i have 5 different iot devices there will be 5 different messages every minute. The next minute there will be a new message from each of the iot devices. it would be fine if the mqtt server discards the previous messages and just keep the current ones.  So that any other clients wanting to receive this json messages only receive the latest one.  Should I set the setRetained(false)?

Looking at my code, do you have any suggestions?

thanks

**Comment by hylkevds** [comment]
The cleanSession setting on the publishing client should not matter, since the publishing client probably doesn't subscribe to any topics.

If you want your listening clients to receive the last published value when they subscribe, you should publish with `retained=true` and `cleanSession=false`. If the messages are published with `retained=false` your clients would have to connect, and wait for the next value to be published before receiving anything.

`retained=false` and `cleanSession=false`:
1. Publisher publishes A messages
1. Client connects
1. Client subscribes
1. Published publishes B messages
1. Client receives B messages
1. Client disconnects (with or without unsubscribing)
1. Publisher publishes C messages
1. Client reconnects
1. Client subscribes
1. Published publishes D messages
1. Client receives D messages

`retained=true` and `cleanSession=false`:
1. Publisher publishes A messages
1. Client connects
1. Client subscribes and receives last message of set A
1. Published publishes B messages
1. Client receives B messages
1. Client disconnects (with or without unsubscribing)
1. Publisher publishes C messages
1. Client reconnects
1. Client subscribes and receives last message of set C
1. Published publishes D messages
1. Client receives D messages


cleanSesson=true is for when your clients want to receive all messages that were send while the clients are disconnected:

`retained=false` and `cleanSession=true`:
1. Client connects
2. Client subscribes
3. Client disconnects (without unsubscribing!)
4. Publisher publishes X messages
5. Client reconnects, and directly received X messages he missed while being disconnected.

**Comment by arifainchtein** [comment]
@hylkevds thanks for the info.  I am going to set cleanSession=false and hopefully that will fix the problem. Will update this issue as soon as  I get some insight of how this change affects the performance.  thanks again

**Comment by arifainchtein** [comment]
Hello,
Just to report that indeed, setting the cleanSession to false did the trick. Here is the code that i changed in the Paho client

`mqtt.connect({onSuccess: onConnect, onFailure: onFailure, cleanSession:false});`

have not crashed in days.

thanks again
