### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by manish9161** [moquette-io/moquette#525]
### Expected behavior
Should work in Android API 21 or below

### Actual behavior

Crash in below Android API 24

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
        at io.moquette.server.netty.NettyAcceptor.initialize(NettyAcceptor.java:145)
        at io.moquette.server.Server.startServer(Server.java:183)
        at io.moquette.server.Server.startServer(Server.java:153)
        at com.petpoojaandroidpos.httpserver.MqttBroker.startMqttServer(MqttBroker.kt:28)

**Comment by andsel** [comment]
Moquette is not Android compatible
