### ISSUE TITLE
NullPointerException in CTrie.evaluate

### ISSUE THREAD

**Issue by hylkevds** [moquette-io/moquette#529]
### Expected behavior
No exceptions when publishing a message

### Actual behavior
```
09:28:02.560 [nioEventLoopGroup-3-1] ERROR   i.m.broker.NewNettyMQTTHandler - Error processing protocol message: PUBLISH
java.lang.NullPointerException: null
	at io.moquette.broker.subscriptions.CTrie.evaluate(CTrie.java:58)
	at io.moquette.broker.subscriptions.CTrie.recursiveMatch(CTrie.java:70)
	at io.moquette.broker.subscriptions.CTrie.recursiveMatch(CTrie.java:86)
	at io.moquette.broker.subscriptions.CTrie.recursiveMatch(CTrie.java:86)
	at io.moquette.broker.subscriptions.CTrie.recursiveMatch(CTrie.java:65)
	at io.moquette.broker.subscriptions.CTrieSubscriptionDirectory.matchWithoutQosSharpening(CTrieSubscriptionDirectory.java:67)
	at io.moquette.broker.subscriptions.CTrieSubscriptionDirectory.matchQosSharpening(CTrieSubscriptionDirectory.java:72)
	at io.moquette.broker.PostOffice.publish2Subscribers(PostOffice.java:207)
	at io.moquette.broker.PostOffice.receivedPublishQos2(PostOffice.java:244)
	at io.moquette.broker.MQTTConnection.processPublish(MQTTConnection.java:361)
	at io.moquette.broker.MQTTConnection.handleMessage(MQTTConnection.java:77)
	at io.moquette.broker.NewNettyMQTTHandler.channelRead(NewNettyMQTTHandler.java:58)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.broker.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:46)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.broker.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.broker.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:51)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
### Steps to reproduce
git clone git@github.com:FraunhoferIOSB/FROST-Server.git
cd FROST-Server
mvn install

https://travis-ci.org/github/FraunhoferIOSB/FROST-Server/jobs/686452716

It seems it does not always happen on my machine, but it's very reproducable on Travis. I've not been able to debug Moquette, since it does not compile on java 11.

### Moquette MQTT version
0.13

### JVM version (e.g. `java -version`)
11.0.7

**Comment by hylkevds** [comment]
I've made a little minimal test project / torture test for this problem that will usually give the above exception in a few seconds:

https://github.com/hylkevds/moquetteTests

What it does is:

- It spins up a Moquette
- It creates 1 client for publishing
- It creates 10 threads for publishing data
  - each publishes on 1 topic
  - each publishes as fast as it can
- It creates 1 (or more) thread for listening, each with its own client.
  In a loop they:
  - connect, 
  - subscribe to all topics
  - count received messages for 2000 ms
  - unsubscribe from all topics
  - disconnect
  - sleep for 100 ms

If you increase the listener count to 10 or so, I also see lots of other exceptions and netty weirdness, but with just 1 client I only get the above exception.

I hope that helps you in finding the issue!

**Comment by hylkevds** [comment]
I managed to get moquette to compile with the help of PR https://github.com/moquette-io/moquette/pull/498 and did a bit of debugging.
If the exception happens, it's because it is evaluating on a TNode, and I think TNodes should be excluded when fetching subscriptions from children: 

in CTrie.java:86
```
if (subInode.mainNode() instanceof TNode) {
    continue;
}
```

But I've not fully gone through all details of your CTrie implementation, so I'm not sure this has no side effects.

**Comment by hylkevds** [comment]
This seems to be a duplicate of #505
The solution proposed there is essentially the same: Don't process TNodes.

The test project above is still useful for finding problems though :)

**Comment by andsel** [comment]
Hi @hylkevds this issue is fixed with PR #564

**Comment by hylkevds** [comment]
Great!
With this merge, our FROST-Server integration tests fully finish when using .14-SNAPSHOT.
Do you have any idea on when you'll release .14?

**Comment by andsel** [comment]
Version 0.14 is out https://github.com/moquette-io/moquette/releases/tag/v0.14.
