### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by javawmw** [moquette-io/moquette#593]
### Minimal yet complete reproducer code (or URL to code) or complete log file
[broker-server:172.16.72.88:6971] [,] 2021-04-07 19:50:08.389 ERROR 28620 [nioEventLoopGroup-5-6] io.moquette.broker.NewNettyMQTTHandler Unexpected exception while processing MQTT message. Closing Netty channel. CId=null

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
### Moquette MQTT version
0..14
### JVM version (e.g. `java -version`)
jdk 1.8
### OS version (e.g. `uname -a`)
centos 7

**Comment by hylkevds** [comment]
It seems your client is closing the connection without properly disconnecting from the server.
Can't say much more than that without more details, and preferably a repeatable test-case.
