### ISSUE TITLE
UnresolvedAddressException in Ubuntu20

### ISSUE THREAD

**Issue by begone1992** [moquette-io/moquette#647]
### Expected behavior
In Ubuntu 20 MQTT is configured in 1883 port, and mqtt-borker server should start without any problem.

### Actual behavior
When mqtt-broker server is trying to start in Ubuntu 20 there is throw exception.
SEVERE: An interruptedException was caught while initializing integration. Protocol=TCP MQTT

java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:104)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:217)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce
try to start MQTT server in Ubuntu 20 with port 1883.

### Moquette MQTT version
moquette-broker-0.15

### JVM version (e.g. `java -version`)
1.8.0_312

### OS version (e.g. `uname -a`)
Ubuntu 20

**Comment by hylkevds** [comment]
That sounds like a mis-configured setup. I'm using Mint, based on Ubuntu 20.04.3 LTS (Focal Fossa) and it works fine here.
Can you be more precise in your description of how you are starting Moquette?

**Comment by begone1992** [comment]
Hi,
First of all this is my configuration.
configProps.put(BrokerConstants.WEB_SOCKET_PATH_PROPERTY_NAME, "1884");
			configProps.put(BrokerConstants.SSL_PORT_PROPERTY_NAME, "8080");
			configProps.put(BrokerConstants.HOST_PROPERTY_NAME, ipAddress);
			configProps.put(BrokerConstants.PASSWORD_FILE_PROPERTY_NAME, "");
			configProps.put(BrokerConstants.ALLOW_ANONYMOUS_PROPERTY_NAME, Boolean.TRUE.toString());
			configProps.put(BrokerConstants.AUTHENTICATOR_CLASS_NAME, "");
			configProps.put(BrokerConstants.AUTHORIZATOR_CLASS_NAME, "");
			configProps.put(BrokerConstants.NETTY_MAX_BYTES_PROPERTY_NAME,
	            String.valueOf(BrokerConstants.DEFAULT_NETTY_MAX_BYTES_IN_MESSAGE));

After that I initialize IConfig.
IConfig myServerConfig = new MemoryConfig(configProps);

And then I initialize Server and just start it with PublisherListener.
Server _mqttBroker = new Server();
final List<? extends InterceptHandler> userHandlers = Arrays.asList(new PublisherListener());
_mqttBroker.startServer(server_config, userHandlers);

**Comment by hylkevds** [comment]
Whatever you are passing to Moquette in this line does not resolve:
```
 configProps.put(BrokerConstants.HOST_PROPERTY_NAME, ipAddress);
```
Does it work without that line?

**Comment by begone1992** [comment]
I get hostname with command "hostname -I" and then pass it in that line. So at the moment I am using this IP address 10.0.2.15 in that line.

**Comment by hylkevds** [comment]
Just leave that line out, or make sure that IP address resolves.

**Comment by begone1992** [comment]
Yes, It started now. But why is this line causing a problem? Because the same configuration is working in Ubuntu 16.

**Comment by hylkevds** [comment]
Apparently your Ubuntu 20 does not add your local IP addresses to the hosts file, leaving them unresolvable.
