### ISSUE TITLE
compile error v0.15

### ISSUE THREAD

**Issue by worker24h** [moquette-io/moquette#666]
### Expected behavior
mvn clean package

### Actual behavior
mvn clean package

### Minimal yet complete reproducer code (or URL to code) or complete log file
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:200)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:40)
	at com.sun.tools.javac.main.Main.compile(Main.java:470)

### Moquette MQTT version
v0.15

### JVM version (e.g. `java -version`)
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

### OS version (e.g. `uname -a`)
Darwin bogon 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64

**Comment by andsel** [comment]
`0.15` is no more supported, please test with never version.
