### ISSUE TITLE
Does not check for illegal wildcard usage in topic filters in SUBSCRIBE, UNSUBSCRIBE, and PUBLISH

### ISSUE THREAD

**Issue by ckrey** [moquette-io/moquette#68]
> [MQTT-3.3.2-2]
> The Topic Name in the PUBLISH Packet MUST NOT contain wildcard characters.
> 
> [MQTT-4.7.1-2]
> The multi-level wildcard character MUST be specified either on its own or following a topic level separator. In either case it MUST be the last character specified in the Topic Filter.
> 
> [MQTT-4.7.1-3]
> The single-level wildcard can be used at any level in the Topic Filter, including first and last levels. Where it is used it MUST occupy an entire level of the filter.

**Comment by andsel** [comment]
Hi,
the SubscriptionsStoreTest already validate these cases, and SUBACK after a SUBSCRIBE return fail for the topic. How can I reproduce it?

**Comment by ckrey** [comment]
Here is what happens when UNSUBSCRIBE '#abc': reply is UNSUBACK. Would expect connection close

```
181219 [pool-1-thread-1] ERROR SubscriptionsStore  -
java.text.ParseException: Bad format of topic, invalid subtopic name: #abc
    at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.parseTopic(SubscriptionsStore.java:339)
    at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.findMatchingNode(SubscriptionsStore.java:126)
    at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.removeSubscription(SubscriptionsStore.java:161)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processUnsubscribe(ProtocolProcessor.java:591)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
181247 [pool-1-thread-1] INFO  ProtocolProcessor  - replying with UnsubAck to MSG ID 2
```

**Comment by ckrey** [comment]
Tests in SUBSCRIBE are correct, I had a flaw in my test routines. SUBSCRIBES returns 0x80.

**Comment by ckrey** [comment]
PUBLISH accepts illegal wildcards

**Comment by ckrey** [comment]
with new 0.8 version the only remaining problem is the wrong positive feedback when trying to UNSUBSCRIBE an illegal topic e.g. '#abc' (see above)

**Comment by andsel** [comment]
HI Christoph,
I've read again the specification about format of the topicFilter for UNSUBSCRIBE, but I can't find  any word about bad format of the topicFilter and closing connection. Do you have any hint from the MQTT google group?

**Comment by ckrey** [comment]
It says it must contain a Topic Filter, #abc is an invalid topic filter, as you cannot give negative feedback on UNSUBSCRIBE, closing the connection would be appropriate

> The Payload of an UNSUBSCRIBE packet MUST contain at least one Topic Filter. An UNSUBSCRIBE packet with no payload is a protocol violation [MQTT-3.10.3-2]. See section 4.8 for information about handling errors.
> 
> 4.7.1.2 Multi-level wildcard
> The number sign (‘#’ U+0023) is a wildcard character that matches any number of levels within a topic. The multi-level wildcard represents the parent and any number of child levels. The multi-level wildcard character MUST be specified either on its own or following a topic level separator. In either case it MUST be the last character specified in the Topic Filter [MQTT-4.7.1-2].
> 
> 4.8 Handling errors
> Unless stated otherwise, if either the Server or Client encounters a protocol violation, it MUST close the Network Connection on which it received that Control Packet which caused the protocol violation [MQTT-4.8.0-1].

**Comment by andsel** [comment]
Thanks for your interpretation, fixed broker in this way, you can find the latest snapshot version in previous Dropbox shared folder, to redo the test.
Thanks a lot
