### ISSUE TITLE
Bizzare error when wrong username/password provided to the server

### ISSUE THREAD

**Issue by nissimpradhan** [moquette-io/moquette#88]
When an MQTTClient with wrong username and password tries to connect to the server. There is a bizzare NullPointer error subsequently causing the server to not let any other normal MQTT client connect either....

The error occurs because, a lostconnection event is fired, Although any connections wasn't lost yet. And when this event is processed, clientID cannot be extracted from the evt variable (LostConnectionEvent) on the void processConnectionLost(LostConnectionEvent evt) method in ProtoclProcessor class.

The log file is given below:

```
17:16:29,881 INFO  [org.eclipse.moquette.server.netty.NettyMQTTHandler] (nioEventLoopGroup-3-1) Received a message of type CONNECT
17:16:29,881 DEBUG [org.eclipse.moquette.spi.impl.SimpleMessaging] (nioEventLoopGroup-3-1) disruptorPublish publishing event ProtocolEvent wrapping CONNECT
17:16:29,881 INFO  [org.eclipse.moquette.spi.impl.SimpleMessaging] (pool-4-thread-1) onEvent processing messaging event from input ringbuffer ProtocolEvent wrapping CONNECT
17:16:29,881 DEBUG [org.eclipse.moquette.spi.impl.ProtocolProcessor] (pool-4-thread-1) CONNECT for client <TestClient1>
17:16:29,881 INFO  [org.eclipse.moquette.spi.impl.security.FileAuthenticator] (pool-4-thread-1) username or password was null
17:16:29,896 DEBUG [org.eclipse.moquette.spi.impl.SimpleMessaging] (nioEventLoopGroup-3-1) disruptorPublish publishing event org.eclipse.moquette.spi.impl.events.LostConnectionEvent@73a97861
17:16:29,896 INFO  [org.eclipse.moquette.spi.impl.SimpleMessaging] (pool-4-thread-1) onEvent processing messaging event from input ringbuffer org.eclipse.moquette.spi.impl.events.LostConnectionEvent@73a97861
17:16:29,896 SEVERE [com.lmax.disruptor.FatalExceptionHandler] (pool-4-thread-1) Exception processing: 1 org.eclipse.moquette.spi.impl.ValueEvent@56798a15: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) [rt.jar:1.8.0_40]
    at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) [rt.jar:1.8.0_40]
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:592) [moquette-broker.jar:]
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:177) [moquette-broker.jar:]
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1) [moquette-broker.jar:]
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) [disruptor-3.3.2.jar:]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]

17:16:29,896 ERROR [stderr] (pool-4-thread-1) Exception in thread "pool-4-thread-1" java.lang.RuntimeException: java.lang.NullPointerException

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:147)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at java.lang.Thread.run(Thread.java:745)

17:16:29,896 ERROR [stderr] (pool-4-thread-1) Caused by: java.lang.NullPointerException

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:592)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:177)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:1)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)

17:16:29,896 ERROR [stderr] (pool-4-thread-1)   ... 3 more
```

I fixed it by checking if clientID String in evt was null or not before processing the event. It works fine after that. But i wanted to inform you about the bug

**Comment by andsel** [comment]
Fixed with commit f7466fd9683a22f81a786088ba10f7a3779bbdb6 it was due to a bad creation of LostConnectionEvent in case the channel becomes inactive on a not correctly completed CONNECT message.
