### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: 

### ISSUE THREAD

**Issue by dc198798** [moquette-io/moquette#9]
io.netty.handler.codec.CorruptedFrameException: Received a message with fixed header flags (a) != expected (2)
    at org.dna.mqtt.moquette.parser.netty.DemuxDecoder.genericDecodeCommonHeader(DemuxDecoder.java:62)
    at org.dna.mqtt.moquette.parser.netty.DemuxDecoder.decodeCommonHeader(DemuxDecoder.java:44)
    at org.dna.mqtt.moquette.parser.netty.PubRelDecoder.decode(PubRelDecoder.java:36)
    at org.dna.mqtt.moquette.parser.netty.MQTTDecoder.decode(MQTTDecoder.java:71)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:332)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:318)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:332)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:318)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:253)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:332)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:318)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:478)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:744)

**Comment by andsel** [comment]
Please could you provide a way to reproduce the bug, a stack trace without any other information or log is not an acceptable issue report

**Comment by andsel** [comment]
Closed because the user doesn't provided any information on how to reproduce it

**Comment by makleyston** [comment]
Hello, I have the same problem.
I'm using the Lua MQTT library for publisher and subscriber on Moquette.
I have a problem to subscribe, because an exception is thrown: "WARN NettyMQTTHandler - Error decoding a packet, probably a mapped packet, message: Received a message with fixed header flags (0)! = Expected (2)".
I test with other brokers and the result is successful.
What could it be?

**Comment by leecoder** [comment]
+1
