### ISSUE TITLE
NettyAcceptor  - Severe error during pipeline creation

### ISSUE THREAD

**Issue by unclezhao** [moquette-io/moquette#91]
I want to test SSL pub and sub. But just one of pub or sub can connected to moquette server, when another connected, there was an exception like this:

```
1630 [main] INFO  NettyAcceptor  - Starting SSL on port 8883
1632 [main] INFO  NettyAcceptor  - Server binded host: 0.0.0.0, port: 8883
1632 [main] INFO  NettyAcceptor  - SSL is disabled
Server started, version 0.7
10030 [pool-1-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <SSLSubscribeClientTest>
10070 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <SSLSubscribeClientTest>
10105 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <SSLSubscribeClientTest> with clean session true
10106 [pool-1-thread-1] INFO  ProtocolProcessor  - <SSLSubscribeClientTest> subscribed to topic <MQTT> with QoS 0 - MOST_ONE
17551 [nioEventLoopGroup-3-2] ERROR NettyAcceptor  - Severe error during pipeline creation
io.netty.channel.ChannelPipelineException: io.netty.handler.ssl.SslHandler is not a @Sharable handler, so can't be added or removed multiple times.
        at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:463)
        at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:135)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:128)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
        at org.eclipse.moquette.server.netty.NettyAcceptor$4.init(NettyAcceptor.java:221)
        at org.eclipse.moquette.server.netty.NettyAcceptor$1.initChannel(NettyAcceptor.java:129)
        at org.eclipse.moquette.server.netty.NettyAcceptor$1.initChannel(NettyAcceptor.java:124)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:445)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:377)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:421)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
65630 [pool-1-thread-1] INFO  ProtocolProcessor  - Lost connection with client <SSLSubscribeClientTest>
72509 [nioEventLoopGroup-3-1] ERROR NettyAcceptor  - Severe error during pipeline creation
io.netty.channel.ChannelPipelineException: io.netty.handler.ssl.SslHandler is not a @Sharable handler, so can't be added or removed multiple times.
        at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:463)
        at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:135)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:128)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
        at org.eclipse.moquette.server.netty.NettyAcceptor$4.init(NettyAcceptor.java:221)
        at org.eclipse.moquette.server.netty.NettyAcceptor$1.initChannel(NettyAcceptor.java:129)
        at org.eclipse.moquette.server.netty.NettyAcceptor$1.initChannel(NettyAcceptor.java:124)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:445)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:377)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:421)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

my subscribe code:

public class MqttSSLSubscribeSample {

```
public static SSLSocketFactory configureSSLSocketFactory() throws Exception {
    KeyStore ks = KeyStore.getInstance("JKS");
    InputStream jksInputStream = new FileInputStream("subclientkeystore.jks");
    ks.load(jksInputStream, "passwd0rfv".toCharArray());

    KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    kmf.init(ks, "passwd0edc".toCharArray());

    TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    tmf.init(ks);

    SSLContext sc = SSLContext.getInstance("TLS");
    TrustManager[] trustManagers = tmf.getTrustManagers();
    sc.init(kmf.getKeyManagers(), trustManagers, null);

    SSLSocketFactory ssf = sc.getSocketFactory();
    return ssf;
}

public static void main(String[] args) throws Exception {
    String topic        = "MQTT";
    int qos             = 0;
    String broker       = "ssl://localhost:8883";
    String clientId     = "SSLSubscribeClientTest";

    try {
        final MqttClient mqttClient = new MqttClient(broker, clientId, new MemoryPersistence());
        SSLSocketFactory ssf = configureSSLSocketFactory();
        MqttConnectOptions options = new MqttConnectOptions();
        options.setSocketFactory(ssf);
        options.setCleanSession(true);

        mqttClient.setCallback(new MqttCallback() {

            @Override
            public void messageArrived(String topic, MqttMessage message) throws Exception {
                try {
                    System.out.println(topic + " => " + new String(message.getPayload()));
                } catch (RuntimeException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void deliveryComplete(IMqttDeliveryToken token) {
                // not used
            }

            @Override
            public void connectionLost(Throwable cause) {
                System.out.println("Connection lost: " + cause.getLocalizedMessage());
            }
        });
        mqttClient.connect(options);
        mqttClient.subscribe(topic, qos);

    } catch (MqttException e) {
        e.printStackTrace();
    }
}
```

}

my publisher code:

```
public class MqttSSLPublishSample {

    public static SSLSocketFactory configureSSLSocketFactory() throws Exception {
        KeyStore ks = KeyStore.getInstance("JKS");
        InputStream jksInputStream = new FileInputStream("/pubclientkeystore.jks");
        ks.load(jksInputStream, "passwd0edc".toCharArray());

        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(ks, "password".toCharArray());

        TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(ks);

        SSLContext sc = SSLContext.getInstance("TLS");
        TrustManager[] trustManagers = tmf.getTrustManagers();
        sc.init(kmf.getKeyManagers(), trustManagers, null);

        SSLSocketFactory ssf = sc.getSocketFactory();
        return ssf;
    }

    public static void main(String[] args) throws Exception {

        String topic        = "MQTT";
        String content      = "Message from MqttPublishSample " + System.currentTimeMillis();
        int qos             = 0;
        String broker       = "ssl://localhost:8883";
        String clientId     = "SSLPublishClientTest";

        try {
            String tmpDir = System.getProperty("java.io.tmpdir");
            MqttDefaultFilePersistence dataStore = new MqttDefaultFilePersistence(tmpDir);

            MqttClient client = new MqttClient(broker, clientId, dataStore);
            SSLSocketFactory ssf = configureSSLSocketFactory();
            MqttConnectOptions options = new MqttConnectOptions();
            options.setSocketFactory(ssf);
//            client.connect(options);

            options.setCleanSession(true);
            System.out.println("Connecting to broker: "+broker);
            client.connect(options);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            MqttMessage message = new MqttMessage(content.getBytes());
            message.setQos(qos);
            client.publish(topic, message);
            System.out.println("Message published");
            client.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
    }
}
```

**Comment by runafter** [comment]
io.netty.handler.ssl.SslHandler cannot share with another pipeline.
So I modified org.eclipse.moquette.server.netty.NettyAcceptor temporary.
ref https://github.com/runafter/moquette/commit/2ae53410082aa3d54b069d76b2e61d63cb1d957c

**Comment by andsel** [comment]
Fixed with the PR from @runafter
